### ISSUE TITLE
warn when there is an unfinished command state 

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#1016]
Recognize when a git town command is in progress and prompt the user to confirm that this action has been finished / aborted manually.

Example:

* Run `git sync`
* Hit a conflict
* Take one of the following actions
  * Resolve the conflict and run `git sync` (this is something I have done many times)
    * It should prompt that a sync is in progress. Provide options to the user to quit, abort sync,  continue sync, discard state and run fresh
  * Leave, come back, run `git ship other`. Prompt that a sync is in progress, provide options to quit or discard state and run fresh
  * Run `git town status` to be told if any command is in progress

@kevgo thoughts?

**Comment by kevgo** [comment]
I like this a lot and was thinking about the same. I think simply aborting the current command if there is an unfinished one might be enough here for starters.

What about also creating `git-town continue` and `git-town abort` commands to continue or abort the previous operation?
