### ISSUE TITLE
GitLab PR on Windows

### ISSUE THREAD

**Issue by whitebear-gh** [Originate/git-town#1017]
Hi, when creating pr using following command: 

`git town new-pull-request`

I get following error:

[feature-branch] git fetch --prune

cd C:/Workspace/Repos/priv/GitLab/repo

```
[feature-branch] git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.

[master] git rebase origin/master
Current branch master is up to date.

[master] git checkout feature-branch
Switched to branch 'feature-branch'
Your branch is up-to-date with 'origin/feature-branch'.

[feature-branch] git merge --no-edit origin/feature-branch
Already up-to-date.

[feature-branch] git merge --no-edit master
Already up-to-date.

cd C:\Workspace\Repos\priv\GitLab\repo

  Error
  Cannot open a browser.
  If you think this is a bug,
  please open an issue at https://github.com/Originate/git-town/issues
  and mention your OS and browser.

```

Do you have any suggestions?

**Comment by charlierudolph** [comment]
Git Town looks for a command that would open a browser to the provided url. [Here](https://github.com/Originate/git-town/blob/v4.2.1/src/util/util.go#L60) are the current commands it uses. On your OS, do you know of a command we could use to open a browser?

**Comment by kevgo** [comment]
I think on Windows the command to open a new browser window is `explorer "http://google.com"`, see https://stackoverflow.com/questions/3739327/launching-a-website-via-windows-commandline.

@whitebear-gh, we don't have access to a Windows machine. Can you please run the command above (`explorer "http://google.com"`) and confirm to us that it opens a browser window showing the Google homepage?

**Comment by whitebear-gh** [comment]
Hi guys, thanks for responding. Yes it's true - command is `explorer "url"` and I confirm that it opens browser from my command line. Is adding it to listed command list enough? I would like to create PR but I have no experience with go so far.

**Comment by whitebear-gh** [comment]
Hi guys, thanks for fixing this one. When can we expected new release with newest fixes?

**Comment by smeijer** [comment]
Was this ever published? Upon `git town repo` (Windows + Chrome), I'm still getting:

```bash
  Error
  Cannot open a browser.
  If you think this is a bug,
  please open an issue at https://github.com/Originate/git-town/issues
  and mention your OS and browser.
```

**Comment by kevgo** [comment]
@smeijer the current version of Git Town runs `start <url>` on Windows. Can you please run something like `start http://google.com` in your terminal and see if that works on your machine? This command and `git town repo` work on my Windows 10 machine with Firefox when I run this in the Windows CMD terminal. 

Also, please provide more info about your environment (Windows version, which terminal you use, what the URL of your repo is, etc).
