### ISSUE TITLE
Feature Request: autosquash my branch

### ISSUE THREAD

**Issue by JayAndCatchFire** [Originate/git-town#1026]
I often want to squash all my commits down to a single commit before I create a pull request.  How about a command to do that for me?

**Comment by kevgo** [comment]
I think this feature would be mostly needed when making a PR from a forked repo against the upstream. Many repos have the guidelines that PRs must be in the form of a single commit. For PRs within a repo I see it as optional, since `git ship` squashes all the commits for you already. 

I also am concerned about running into repeated merge conflicts when always squashing everything all the time. So, it sounds like this should be enabled by a configuration option like `git-town.squash-upstream-pr` and `git-town.squash-pr`.

**Comment by JayAndCatchFire** [comment]
Maybe "autosquash" wasn't the right term. I wasn't suggesting that git-town would squash my commits automatically as part of the pr command. I was just hoping for a command to squash all the commits in a branch faster than having to do an interactive rebase. Git allows you to do an autosquash already, but from my understanding you have to leave certain keywords in your commit messages ahead of time. I don't usually have that level of foresight.

**Comment by kevgo** [comment]
We were thinking about a `git squash-branch` command in the past, but didn't find a good use case for it as a stand-alone command. 

Git Town is not just a collection of nifty Git tools (that's what [git-extras](https://github.com/tj/git-extras) is), but an opinionated collection of Git tools that work together to allow robust and high-level workflows. 

If somebody wants to squash the commits on a branch, it would be either as part of creating a pull-request or as part of shipping a branch. So those commands should do the squash.

If we require users to manually squash commits, that means they would sometimes do it and sometimes forget it, and that is not a robust workflow.

**Comment by JayAndCatchFire** [comment]
I can appreciate that. Perhaps I've been using git town incorrectly then. When I try using the pr command, it fails due to my repos being hosted on a Bitbucket Server instance. But this is outside the scope of my ticket.

**Comment by kevgo** [comment]
Let's fix broken PRs. Is your issue related to #1017?

**Comment by JayAndCatchFire** [comment]
No, I don't think it's related.  My repos are hosted on my company's install of Bitbucket Server, which resides at a URL matching the pattern http://stash.companyname.com/.  I don't see any way to configure Git Town to allow it to use that URL for PRs.

**Comment by kevgo** [comment]
That sounds a lot like what #1019 is about. Definitely on our list to add a config option to tell Git Town that `stash.companyname.com` is a BitBucket server.
