### ISSUE TITLE
ability to store API tokens separately from the rest of the Git Town configuration

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#1031]
The API tokens used by `git ship` are user specific and should not be stored together with the rest of the Git Town configuration.

#### Background

I store [my config files](https://github.com/kevgo/dot-files) in Git. This means they cannot contain confidential data like my Github API token. This value should be stored in a separate file that is git-ignored.

**Comment by charlierudolph** [comment]
I don't believe the git config is ever pushed up to the remote. We have the setup that up for each machine so I don't think there is any issue here

**Comment by kevgo** [comment]
This is only valid if #1030 gets implemented

**Comment by charlierudolph** [comment]
Can this be listed as an issue of #1030 then instead of being a separate issue

**Comment by kevgo** [comment]
Okay, done

**Comment by charlierudolph** [comment]
Thanks!
