### ISSUE TITLE
Sync / rebase from fork

### ISSUE THREAD

**Issue by Siilwyn** [Originate/git-town#1033]
Hi there, thank you for making this awesome CLI tool, saves a ton of time working with git!

I'm wondering if I'm missing something or if it's not present (I'm on the latest release that has a `deb` file), how would I go through the following flow?

1. Fork a repository
2. Create a feature branch (`git town hack`)
3. Work on it for a while
4. Rebase feature branch on master of the original repository

Especially syncing with the fork master is something that seems painful with normal git commands:

0. `git pull --rebase fork feature`
1. `git checkout master`
2. `git pull --rebase origin master`
3. `git checkout feature`
4. `git rebase master feature`

**Comment by charlierudolph** [comment]
From https://github.com/Originate/git-town/blob/v4.2.1/documentation/commands/sync.md

> Additionally, when there is a remote upstream, the main branch is synced with its upstream counterpart.

Not the most clear, but the name `upstream` came from this github article https://help.github.com/articles/fork-a-repo/ under the section "Keep your fork synced". Thus is you add the original as a remote named `upstream`, and run git sync, it should bring you master branch up to date with the remote and sync your feature branch with master

**Comment by Siilwyn** [comment]
:tada: awesome! I'll go with the `upstream` naming.
