### ISSUE TITLE
use https://github.com/toqueteos/webbrowser to open browser

### ISSUE THREAD

**Issue by wsw0108** [Originate/git-town#1061]
https://github.com/toqueteos/webbrowser

**Comment by charlierudolph** [comment]
Hmm. I think we should take a different approach here. I'd prefer we back off on what built-in browser commands and add in a way for a user to specify their own command that opens a browser.

**Comment by charlierudolph** [comment]
Sorry I misunderstood your suggestion. The library looks but I do think it would be nice if we also allowed the user to provide their own browser command if need be. 

@kevgo why did we add the browser types? I understand adding start for windows support but don't think we needed all the others.

**Comment by kevgo** [comment]
@wsw0108 thanks for the pointer, the library looks nice! We were entertaining the idea of building something like this on our own at some point. Good to see that such things exist!

@charlierudolph We are following [what Github is doing](https://github.com/github/hub/blob/master/utils/utils.go#L48-L49) in their `hub` CLI tool. The additional browser commands are necessary for edge cases. Linux for example has a much larger variety of browsers and ways to launch them, based on the installed desktop environment etc. Also, not everybody has one of the mainstream browsers installed (as Opera users can attest).

I am fine allowing the user to specify a custom command to launch browsers, if there is strong demand for such a feature. So far I am not aware of any requests in that area. If we ever do this, we should provide reasonable defaults to launch commonly known browsers on our own. The less configuration people have to do to use Git Town, the better. It should just work out of the box for almost all people.
