### ISSUE TITLE
git-town version 6.0.0 reports its version as 5.1.0

### ISSUE THREAD

**Issue by kelbyers** [Originate/git-town#1098]
I just downloaded `git-town-windows-amd64.exe` from the releases page, under release `v6.0.0`. When I run the `version` command, it reports that it is version `5.1.0`. (I renamed the file after downloading it to keep track of which version it is). Otherwise, it does have the new feature that I am aware of (`new-branch-push-flag`):

```
> Get-FileHash .\git-town-windows-amd64-6.0.0.exe | Format-List


Algorithm : SHA256
Hash      : 3B393D671FEFC227C826D7A651A15C14FA949FFBF989CB688239A8666ED3B36C
Path      : C:\Users\kel\Downloads\git-town-windows-amd64-6.0.0.exe


> .\git-town-windows-amd64-6.0.0.exe version
Git Town 5.1.0
> .\git-town-windows-amd64-6.0.0.exe new-branch-push-flag
false
> .\git-town-windows-amd64-6.0.0.exe hack-push-flag
Error: unknown command "hack-push-flag" for "git-town"
Run 'git-town --help' for usage.
unknown command "hack-push-flag" for "git-town"
```

**Comment by kevgo** [comment]
Thanks for letting us know, we got a [new release](https://github.com/Originate/git-town/pull/1099) cooking to fix this.
