### ISSUE TITLE
hackable perennial branches

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#1141]
On my current project, we have a release branch that is created at the beginning of each week off develop and everything on it goes to production at the end of the week. Any feature that can be released by the end of the week is merged into it. Otherwise, it should be merged into develop and will be released at the end of the next week (merging down from the release branch to develop is automated). 

Based on this, I have the release branch as a perennial branch and want to be able to more easily create new feature branches off it. Currently, I have to check it out and then run `git append`.

I could create a git alias that does this for me but wanted to bring up the idea of some config that make a perennial branch "hackable". Then when running git hack, it prompts the user to pick between the main development branch and the "hackable" perennial branches for what parent to use. There would be no prompt if the no perennial branches are "hackable".

@kevgo thoughts?

**Comment by kevgo** [comment]
Sounds like you guys are using the [nvie model](http://nvie.com/posts/a-successful-git-branching-model), with the twist that most of the development happens on the release branch. Is it correct to say that feature branches are always cut from `release` and almost never from `development`?

Could you make the `release` branch the main branch, and make `development` perennial? Then we could add the ability to ship into a different perennial branch:
- `git ship` ships into the parent branch
- `git ship <branch name>` ships into the given branch (which must be perennial - shipping into feature branches sounds like a mistake most of the time)

**Comment by charlierudolph** [comment]
Small features at the beginning of the week with minimal QA happen on the release branch (deployed to beta nightly). Features developed at the end of the week (Thursday / Friday) or those that need more QA happen on develop (deployed to alpha nightly).

I am not using git ship so my only focus in on hacking a new branch.

**Comment by kevgo** [comment]
That's a pretty cool environment setup! 

So, how would your ideal user experience look like?
- `git hack-from-develop <feature branch name>`
- `git hack-from-release <feature branch name>`

These could be shortened to `git hd` and `git hr`.
In the past we had `git hack <feature name> <parent branch name>`, but that felt cumbersome so we took it out. I would be okay adding this back in, but I personally would probably use bash script shortcuts.

In my opinion, all Perennial branches should be considered "hackable", i.e. one should always be able to cut new feature branches from them. `git hack` is just a shortcut for cutting off the main branch, which per definition is used mostly in this situation.

I think it will be a poor user experience and error-prone to always be asked which branch one wants to hack from.

**Comment by charlierudolph** [comment]
I think my ideal would be something like the old interface but it prompts for the parent branch. I agree this is not a normal flow and want to not change the base scenario. This could be enacted with a flag (`git hack --prompt <feature name>`) or be a new command

**Comment by kevgo** [comment]
I could see a `--hack-from-perennial` or `-p` option that allows the user to select the parent make sense for `git hack`. It would display all perennial branches in a list to chose from. In your case, wouldn't that be only one branch, though?

**Comment by charlierudolph** [comment]
We create a new release branch each week and have another release branch for hotfixes if need be

**Comment by kevgo** [comment]
Thinking more about this, I think `-p` should stand for `--select-parent` and offer a list of all branch names that can be parents (main + all perennial branches).
