### ISSUE TITLE
`git town hack` Any way to fetch upstream only main branch

### ISSUE THREAD

**Issue by iamandrewluca** [Originate/git-town#1144]
I have a use case where upstream has a lot of branches.
IMO When a new feature is starting it should `git fetch upstream {mainBranch}`
Now it wants to fetch all upstream, that has to much size, and need a lot of time to download.

Any way to avoid fetch all the upstream?
Thanks!

**Comment by kevgo** [comment]
I agree that we should only fetch the main branch from upstream. @charlierudolph what do you think?

**Comment by iamandrewluca** [comment]
https://github.com/Originate/git-town/blob/master/src/steps/fetch_upstream_step.go

**Comment by charlierudolph** [comment]
Sounds good. The only edge case to me is if you have a parent branch from upstream that isn’t the main branch but I don’t think we are fetching the upstream in that case anyway.
