### ISSUE TITLE
Prune branches command does not finish with a pull

### ISSUE THREAD

**Issue by shadowhand** [Originate/git-town#1158]
When running `prune-branches` the ~~current~~ main and develop branches should be updated. Right now I often have to do a `git pull` after running `prune-branches` on the development branch.

**Comment by kevgo** [comment]
Having `git prune-branches` update the *current* branch would violate the principle of least surprise and probably cause more confusion than benefits.

We could have it update the **main** branch. @charlierudolph what do you think?

**Comment by shadowhand** [comment]
Right, that's what I meant. Probably both main **and** development.

**Comment by charlierudolph** [comment]
Git town only knows about a single main branch, so I don't know how it would ever sync main and development. 

I don't think there is a need for syncing the main branch before pruning branches and think those are different operations.  If you do these two together often I would suggest creating a git alias the prunes, checkouts out your main branch, and pulls. 

Example:
```
> git config alias.prune-pull  '!sh -c "git prune-branches; git co $(git town main-branch); git pull"'
```
Then you can run `git prune-pull`

**Comment by shadowhand** [comment]
Right, so if I am on the main branch, and I do:

```shell
git town prune-branches
```

It will do a `git fetch` and then delete pruned branches. Assuming I am on the main branch, and that I am behind the upstream, my main branch is now behind upstream HEAD (and running `git status` will say that I am behind). I don't see why doing a `pull` against main branch would be detrimental in this scenario.

**Comment by charlierudolph** [comment]
> One can safely assume that if there are pruned branches, it probably means that main branch is now behind and should be updated. 

Our definition of pruned branches is branches whose upstream has disappeared. This is not dependent on the main branch being behind its upstream. We still to need to fetch to get the updated status of the branch upstreams.

> Is the goal of `prune-branches` not to bring our local copy more in sync with upstream?

That is its goal, but only in relation to the branches whose upstream has disappeared. Syncing the main branch isn't necessary for that.

---

Currently updating the main branch is only done when needed or when running git sync on that branch. I agree with @kevgo that the name does not give any indication that the main branch is updated and think that functionality would be surprising to other users

**Comment by kevgo** [comment]
Hey @shadowhand, when using Git Town's consistently you should never worry about the main branch. I.e. you should never have to run `git status` on the main branch. You can trust that Git Town always does the right thing and updates the main branch when that is really necessary, i.e. when creating a new feature branch or when shipping. 

Following the logic proposed in this ticket, Git Town should *always* update all branches at all times. That feels like taking a good idea too far.
