### ISSUE TITLE
radio list on Windows contains garbled characters

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#1163]
### Context

running `git town config setup` on Windows

### Problem

1. the cursor in the radio list to select the main branch contains a non-printable character:
  ![image](https://user-images.githubusercontent.com/268934/43232425-8a6bcf40-9025-11e8-8cd8-9128010e5c4c.png)

2. the checkboxes in the list to select the perennial branches contain non-printable characters:
  ![image](https://user-images.githubusercontent.com/268934/43232463-cb2dada0-9025-11e8-9a18-700d802c27e2.png)

**Comment by charlierudolph** [comment]
This should be opened as an issue on https://github.com/AlecAivazis/survey
