### ISSUE TITLE
Brew install fails if go version is pinned

### ISSUE THREAD

**Issue by ben-goldberg** [Originate/git-town#1182]
Hi git-town team!

I'm trying to install git-town and running into this problem:

```
>brew install git-town
Error: You must `brew unpin go` as installing git-town requires the latest version of pinned dependencies
```

It's true that my go version is pinned:
```
>brew list --pinned
go
...
```

Is there maybe a workaround here? Do I need to manually install an older version?

**Comment by ben-goldberg** [comment]
Thanks! My short term solution was to un-pin my go version, and then `brew install git-town` worked fine. If I need to re-pin my go version in the future, I'll go the manual install route.

**Comment by kevgo** [comment]
Cool. Closing this, since its an edge case that we don't have the bandwidth to support right now.
