### ISSUE TITLE
Manual selection of git service

### ISSUE THREAD

**Issue by svenihoney** [Originate/git-town#1205]
### Context 

Currently, the upstream service used by e.g. `git town repo` is autodetected by the identity of the used git repository:

> make sure that your SSH identity contains the phrase "github", "gitlab", or
 "bitbucket", so that Git Town can guess which hosting service you use.

In our case we have no possibility to have the gitlab identifier in our ssh identity for our self hosted service. It would be very nice to have a fallback selection or configuration option of the git service in case the autodetection based on the ssh identity fails.

### Benefits

For self hosted instances of e.g. GitLab, it would be possible to use commands like `git town repo` or `git town new-pull-request` even if the ssh identity has no direct hint of the used git service

### Implementaion

A configuration option in the git configuration like `git-town.service = GitLab` would be sufficient for manual setup of the service. An automatic fallback to a selection via survey would be an additional benefit if the autodetection by ssh ID fails.

**Comment by charlierudolph** [comment]
Hello @svenihoney.

This was actually implemented here in #1040 and released in 5.0.0 but it looks like we missed updating some documentation and other documentation updated were accidentally reverted. I'll create a PR to fix our documentation now
