### ISSUE TITLE
git town migrate-child-branches

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#1298]
Had an interesting workflow recently where we don't have a static main branch:

* main branch is release/1.37.0
* after release, main branch becomes release/1.38.0 
* any branches I made off of release/1.37.0 need to be updated accordingly
* currently do this manually with
  * lookup what branches I need to update
  * checkout each branch, run `git town set-parent-branch`

Thoughts on having a tool `git town migrate-child-branches` where you select old parent, then new parent, and all the children of the old parent branch are migrated to having the new parent branch.

When changing main branches, we can also offer to do this for the user as well.

**Comment by charlierudolph** [comment]
Another thought I had is related to #646 

Essentially you could configure your main branch as "origin/HEAD" which sets your branch to be dynamic and on each invocation uses what `origin/HEAD` points to when you run `git branch -r`. That would make my workflow super simple (as we update our main branch with each release) and using that convention, git-town could be useable with zero config.

**Comment by charlierudolph** [comment]
Looked at having the parent be the special origin/HEAD and thing its adds to much complexity. Old parent entries should get automatically deleted if you remove the parent and then you'll be prompted for your parent at the next usage.

**Comment by kevgo** [comment]
An alternative might be to select the branch to ship into.
