### ISSUE TITLE
git prune-branches --undo

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#200]
It would be nice to undo prune-branches if it accidentally deletes a few branches that I didn't want to get deleted. For example branches that I know a coworker is actively developing on.

We will get this for free with #199

**Comment by kevgo** [comment]
This works now thanks to the new architecture.

**Comment by charlierudolph** [comment]
There are no tests for this though. Its also undocumented

**Comment by kevgo** [comment]
I have added #396 for adding specs and documentation.
