### ISSUE TITLE
git ship --green (more robust shipping process)

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#201]
**problem**
- nothing prevents me from accidentally shipping a broken feature branch and breaking main
- we currently rely on devs running the specs manually before shipping

**solution**
- a configuration setting that specifies the test command 
  - this command is run during the shipping workflow
  - if it fails, the ship is aborted
- a configuration setting to enforce only shipping up-to-date feature branches
  - if the master branch gets updated while my tests were running, it restarts the shipping process

**advantages**
- main branch is _never_ broken this way

**side effects**
- shipping can take a much longer time now
- this only works for smaller projects with short spec suites
- that's why it should be configurable

**Comment by charlierudolph** [comment]
A solution for this and #476 could be configuring what CI you're using and providing a token that can be used to get the build status.

**Comment by kevgo** [comment]
Yeah, hooking into the CI system is another option that we should definitely implement as part of this. I think we still need the ability to run tests locally though. Not every GT user might use a CI system yet when using GT. I often start prototyping something locally, and do all the infrastructure setup later once things go into a promising direction.

**Comment by kevgo** [comment]
This is implemented using protected branches on Github, and orthogonal to Git Town's mission of creating and updating branches. Closing.
