### ISSUE TITLE
do not run unnecessary commands

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#230]
I'm uncertain about this idea and want to get your take. What if we don't run merge/rebase commands that don't result in any changes?

Example: syncing a feature branch (when the main branch is sync with its remote, the feature branch is in sync with the main branch and its remote)

Currently

``` bash
$ git sync

[feature] git checkout main
Switched to branch 'main'
Your branch is up-to-date with 'origin/main'.

[main] git fetch --prune

[main] git rebase origin/main
Current branch main is up to date.

[feature] git checkout feature
Switched to branch 'feature'
Your branch is up-to-date with 'origin/feature'.

[feature] git merge origin/feature
Already up-to-date.

[feature] git merge --no-edit main
Already up-to-date.

```

The rebase and merges are unnecessary (this is something we can easily determine), so lets remove them.

``` bash
$ git sync

[feature] git checkout main
Switched to branch 'main'
Your branch is up-to-date with 'origin/main'.

[main] git fetch --prune

[feature] git checkout feature
Switched to branch 'feature'
Your branch is up-to-date with 'origin/feature'.

```

Going one step further we can see that the checkouts are even unnecessary.

``` bash
$ git sync

[feature] git fetch --prune

```

I doubt this would be much faster then the current but would just slim down the output to what the user really cares about, which is what changed.

This would probably result in a bunch of new test cases, but now that we can verify what commands get run it seems very doable.

**Comment by charlierudolph** [comment]
Coming back to this, the problem I ran into when attempting it was it tried to undo the commands that were skipped. Just need commands to have a way to signal they don't need to have its undo step added to the list. Could be done with a global flag that the command conditionally sets and the architecture resets before running a command.

**Comment by kevgo** [comment]
Yeah, we definitely have to sync up the generation of steps and undo steps. I guess the best way to do this is Bash is indeed with a global flag.

**Comment by kevgo** [comment]
@charlierudolph thoughts about closing this as "won't implement"? I don't think either of us is going to get to this in the foreseeable future, since it would require a lot of time that could be spent on lower-hanging fruits. Let's try to keep the list of open issues relevant.

**Comment by charlierudolph** [comment]
Closing due to complexity and little benefit.
