### ISSUE TITLE
allow extracts from non-feature branches

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#276]
From PR #260: 

> @charlierudolph: I would like to update git-extract so it errors if the current branch has no extractable commits (instead of if it on the main branch or a non feature branch). I believe that is easier to understand (and fixes the current poor user experience if trying to extract commits from a feature branch that is even with main).

I would like to see a scenario where extracting commits from a non-feature branch makes sense. Afaik they should be immutable, similar to main, because they are shared history.

**Comment by kevgo** [comment]
I think this can be closed now that git-extract is going away. Also, isn't `git cherry-pick` better for such cases? We don't want to "extract" commits from a perennial branch, just cherry-pick them into the main branch, right?

**Comment by charlierudolph** [comment]
I implemented this already actually. Must have forgot to close it
