### ISSUE TITLE
Optionally install Fish autocomplete during HomeBrew installation

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#284]
> As a developer using Fish shell
> I want the Fish autocompletion installed as part of installing Git Town
> So that I can use this tool efficiently and am as productive as possible.

* check if fish shell is installed
* if it is, copy the git-town autocompletion file in place
* this behavior can be prevented with the option `brew install git-town --without-autocomplete`

**Comment by kevgo** [comment]
This is implemented in https://github.com/kevgo/homebrew-gittown/tree/kg-install-fish-autocomplete, but can only be merged after we release version 0.5

**Comment by charlierudolph** [comment]
You can create the PR for this now

**Comment by kevgo** [comment]
Blocking on #358

**Comment by kevgo** [comment]
Implemented in #358
