### ISSUE TITLE
Bash autocompletion

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#302]
Note: use `bash_completion` to get the path. Example at https://github.com/Homebrew/homebrew/blob/master/Library/Contributions/example-formula.rb

**Comment by charlierudolph** [comment]
Since I know you are now a fish user do you still care about implementing this?

**Comment by kevgo** [comment]
I personally don't care about it, because I will never use this. I'm happy to close this ticket until some Bash user wants to take this on.

**Comment by charlierudolph** [comment]
Cool. Lets close it then

**Comment by kevgo** [comment]
Ok

**Comment by kevgo** [comment]
I am adding a label "postponed" to this ticket, to mark it as technically still valid, but taken off the roadmap for now. This will hopefully allow us to find such tickets easier in the future when we need them again.
