### ISSUE TITLE
Does not work with Originate blog

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#305]
* check out https://github.com/Originate/originate.github.com
* set the main branch to `source`
* create a new blog post
* create a new branch and commit the blog post into it
* run `git pr` from the new branch

expected result: it opens a PR from [my branch] to [source]

actual result: it opens https://github.com/Originate/originatehub.com.git/compare/kg-refactoring-branches-2?expand=1, which is an invalid URL

**Comment by charlierudolph** [comment]
This can be closed. In the future please close with a commit when shipping.

**Comment by kevgo** [comment]
I don't understand what you mean with "close with a commit when shipping".

**Comment by charlierudolph** [comment]
When I ship a branch that closes a feature I have `resolve #<issue number>` in the commit message. That will automatically [close the issue](https://help.github.com/articles/closing-issues-via-commit-messages/).

If the branch only closes part of the issue, I just mention the issue in the commit message with `#<issue number>`

**Comment by kevgo** [comment]
I like that. Can we automate that somehow, in the spirit of #51?

**Comment by charlierudolph** [comment]
I've also been doing that by hand recently

**Comment by kevgo** [comment]
Yeah, but automating it would be so much better!
