### ISSUE TITLE
merge feature specs with and without open changes into one file

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#315]
In order to clean up the excessive number of spec files, we could have the specs with open changes and without open changes in the same file, on top of each other.

Before
* foo_with_open_changes.feature
* foo_without_open_changes.feature

After
* foo.feature

The file would look like this:

```cucumber
Feature: Foo (with open changes)

  Background:
  ...

Feature: Foo (without open changes)

  Background:
  ...

```

This would make it easier to navigate the specs, and the spec file name shorter, at the cost of more content inside the specs. The user value would only show up in the first spec. I think overall that's a worthy tradeoff that makes the code base more manageable.

@charlierudolph @allewun  what do you think?

**Comment by charlierudolph** [comment]
Personally I'm against this because then the files themselves can get quite large. The longest right now are around 80-100 lines and I'd rather keep that then have any that are twice as long. Instead what I have been doing more recently is just create an extra folder.

Before
```
foo_with_open_changes.feature
foo_without_open_changes.feature
```
After
```
+ foo
  + with_open_changes.feature
  + without_open_changes.feature
```

**Comment by kevgo** [comment]
Yes, there are no perfect solutions here. We have to weight file size vs file count. In my opinion the files are getting quite numerous, and the directories are getting nested pretty deep already. Doubling the file size would be acceptable for me if it halves the number of files and avoids an extra level of directory nesting.
