### ISSUE TITLE
git sync: merge the parent branch, not the main branch

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#321]
> As a user working on a feature branch F1 that is cut from another feature branch F
> I want `git sync` to sync my F1 branch against F and not the main branch
> So that I can develop new features based on features currently under review.

* this happens a lot to me, especially when doing smaller and more focussed PRs that take a while to review
* ideally Git Town should recognize this situation on its own and do the right thing, i.e. merge the branch that my feature branch was cut from, not always the main branch
* shipping should still always go into the main branch

**Comment by charlierudolph** [comment]
Branches don't have an idea of who they're parent is. We can search for the branch that is the closest relative of F1 (least number of commits behind F1). When syncing all branches would need to make sure F get synced before F1.

**Comment by charlierudolph** [comment]
Fixed in 252fd3c27c4b520ac7d1bb008883ccaf98d40687 and the following commits
