### ISSUE TITLE
git stash: pop conflicts

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#326]
When there are conflicts while popping the stash it outputs the error messages with abort / continue. 
There should be no error messages.

**Comment by kevgo** [comment]
Can you be more specific? Why should there be no error messages? Because it is the last command?

**Comment by charlierudolph** [comment]
Sample:

```bash
$ git hack new-feature

[old-feature] git fetch --prune
...

[old-feature] git stash -u
Saved working directory and index state WIP on old-feature: 0000000 message
HEAD is now at 0000000 message

[old-feature] git checkout main
Switched to branch 'main'
Your branch is up-to-date with 'origin/main'.

[main] git rebase origin/main
Current branch main is up to date.

[main] git checkout -b new-feature main
Switched to a new branch 'new-feature'

[new-feature] git stash pop
CONFLICT ...

To abort, run "git hack --abort".
To continue after you have resolved the conflicts, run "git hack --continue".

$ git hack --continue
/git-town/src/helpers/script_helpers.sh: line 15: continue_restore_open_changes: command not found
```

If its the last command, we should at least not show a continue. We can leave an abort, but if we are going to support that we need to test that case.

**Comment by kevgo** [comment]
+1  The very same issue happens when implementing #176.

**Comment by charlierudolph** [comment]
Closing in favor of #708 as we do need `--continue` to drop an element from the stash.
