### ISSUE TITLE
Unified naming convention for commits

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#327]
@charlierudolph is using the attached format. Do we want to all use this?

![commits_ _originate_git-town](https://cloud.githubusercontent.com/assets/268934/5624787/70c2ffe4-9521-11e4-8f15-83ac7ae49eba.png)

**Comment by charlierudolph** [comment]
I only used that when it takes multiple PRs to close an issue. Otherwise I used:

![screen shot 2015-01-05 at 9 50 55 pm](https://cloud.githubusercontent.com/assets/1676758/5624933/f63b9e3a-9524-11e4-8aef-7a3cecf25d72.png)

**Comment by kevgo** [comment]
Okay. I like the first version more, since it is more concise. How do you feel about using it all the time?

**Comment by kevgo** [comment]
@charlierudolph Is there an advantage to `resolve #123: foo bar` over `foo bar (#123)`? Like that it connects to the issue better, or closes it automatically?

**Comment by charlierudolph** [comment]
Yes. `resolve #123: foo bar` [closes the issue](https://help.github.com/articles/closing-issues-via-commit-messages/) and `foo bar (#123)` only creates a reference.

**Comment by kevgo** [comment]
Cool. Let's go with the former then. 

https://help.github.com/articles/closing-issues-via-commit-messages states that this can be in the commit message. I prefer to keep it there, and leave the "commit title" clean. The title is limited to 52 characters, which is not a lot. And the issue that is closed is more of a technical issue that doesn't really need to be in the commit title in my opinion.

**Comment by charlierudolph** [comment]
Okay. So the proposed idea is don't mention the issue in the commit title and but the reference in the commit message? (thats how I've been closing the associated PR recently). 

I believe I only mentioned the issue in the commit title to make it easy to generate the release notes when looking at the commits but its just as easy if its in the commit message.

**Comment by kevgo** [comment]
Okay, let's go with mentioning the issue in the body then. #397 adds that to the developer readme

**Comment by kevgo** [comment]
#401 contains further improvements

**Comment by kevgo** [comment]
I think this is done, closing.
