### ISSUE TITLE
git ship: branches in forked repositories

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#336]
Add the ability to run `git ship <username>:<branch>` to ship a forked branch.

It will create a remote for the forked repo (maybe `<username>_fork`), ship the branch, then remove the remote.

**Comment by kevgo** [comment]
:+1:  squash-committing from forked repos would be awesome. I think this requires retaining the author as described in #335.

**Comment by charlierudolph** [comment]
Since github supports squash merging now I don't any need for this anymore.
