### ISSUE TITLE
"git pr" should do a "git sync" before

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#346]
Every time I run `git pr` I run `git sync` before that. How about always syncing before creating a PR. That sounds like the right thing to do anyways.

**Comment by allewun** [comment]
It might be doing too much automatically and startle users. When I'm running `git pr`, I expect a browser window to open with a pull-request form, and that's it -- seeing a bunch of console output when not expecting it is a bit scary.

An alternative might be `git pr --sync` ?

**Comment by charlierudolph** [comment]
I agree. I don't think these should be combined that way. 
I'd be okay with `git sync --pr` which opens a PR afterward syncing.

**Comment by allewun** [comment]
Actually I don't like my original suggestion of `git pr --sync` (and by association also not a fan of `git sync --pr`). While the commands can be used together, they are not intrinsically related imo. Adding all these flags clutters the commands. I think they would be better left as a shell alias for the user.

**Comment by kevgo** [comment]
Okay, closing this idea.
