### ISSUE TITLE
Tests randomly failing on circle

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#354]
Example: https://travis-ci.org/Originate/git-town/builds/47323261

**Comment by allewun** [comment]
Happens locally too

**Comment by kevgo** [comment]
Please add detailed test failure information here if you run into this, so that we can investigate better.

**Comment by kevgo** [comment]
Is this still an issue, or can this be closed now?

**Comment by allewun** [comment]
I've seen tests fail randomly when running locally too though. Might be some race condition with parallelism.

**Comment by kevgo** [comment]
FYI I haven't seen this in a while, and I've been using CI pretty extensively recently.

**Comment by kevgo** [comment]
I haven't seen this is a while. Can we close this?

**Comment by charlierudolph** [comment]
Don't believe we ever saw this after moving to circle so I'm good to close
