### ISSUE TITLE
Remove Gemnasium badge

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#355]
* I don't see the point in tracking devDependencies. The purpose of Gemnasium is to track unpatched security issues in production code. This doesn't apply here. We are perfectly happy using outdated tools to run our specs.
* Dependencies update all the time. This means we will have an ugly yellow badge on our page 90% of the time. The Git Town page should look green.
* Gemnasium doesn't seem to work properly. After updating dependencies yesterday, and pushing that, we have now been falsely yellow for more than a whole day.

Given all this, I'd rather remove the Gemnasium badge. What do you think?

**Comment by charlierudolph** [comment]
Okay, I'm not tied to it. Was meant more to help us know when dependencies are out of date but gemnasium can send you emails for that so I'm fine removing the badge
