### ISSUE TITLE
.git folder getting deleted after running rake

### ISSUE THREAD

**Issue by allewun** [Originate/git-town#366]
Investigate. Possibly due to https://github.com/Originate/git-town/blob/be82092bae1d4a068ecbcce6e0bdedaeabd61868/features/step_definitions/environment_steps.rb#L2 ?

**Comment by charlierudolph** [comment]
Is this in the git town repository or in a one of the repositories being setup by a test?

**Comment by allewun** [comment]
Git Town repo. I think it's related to the WIP work being done in #365. We need to be careful about issuing `rm`s.

**Comment by charlierudolph** [comment]
Can this be closed then?
