### ISSUE TITLE
"git ci" command

### ISSUE THREAD

**Issue by retospect** [Originate/git-town#374]
Curious if this would fit here:
git circle - to work like git pr and open the relevant circle page, or show the state of the last circle build on the command line. 

This could be integrated with git pr as well - providing a warning if the PR was not successful.

Of course, git pr already shows the state of the circle build, so one can get there from here, but it is necessary to create the PR before the icon is visible.

**Comment by kevgo** [comment]
I'm all for making this tool useful, and this situation does happen. But I can imagine that the sheriff of Git Town @charlierudolph won't like this very much. This feels like it should be a Git Town plugin of some sort.

Anyways, I'm throwing my +1 in here. We don't have to advertise this feature on the main page, but could list it in some sort of third-party integration section. Later, when we have a plugin architecture, we could extract this out. Then we can extract all the GitHub, CircleCI, and BitBucket specific features into there. 

@allewun @charlierudolph what do you think?

**Comment by charlierudolph** [comment]
I like it. I think that would be pretty cool

**Comment by kevgo** [comment]
Changed the title to `git ci`, to account for the fact that there might be different CI services (circle, travis, etc).

**Comment by betterworld** [comment]
"ci" is an alias for "commit" in most other version control systems... maybe a different name would be appropriate?
