### ISSUE TITLE
Switch to CircleCI

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#377]
* Travis is flaky, and recently had a week-long breakage that made us look broken without being broken. Circle is stable.
* Travis uses a hidden configuration file, which is a pain to load into the editor. Circle uses a normal one.
* Travis uses a version of Linux that is several years old
* Travis doesn't allow to cache compiled output, thereby forcing us to install and compile ShellCheck from scratch each time. Circle allows to cache this.
* Circle allows to debug issues right on the server. Travis does not.

**Comment by charlierudolph** [comment]
I'm on board.
