### ISSUE TITLE
git ship: Disallow the default commit message

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#382]
When shipping, the default commit message almost never makes sense. When using Git Town, it often reads like

```
Squashed commit of the following:
commit 1c0c837520d5671b59130bbfd8a2020dea58e20e
Merge: e4a56b3 4be83e3
Author: Nir Shtuhl <shtuhl.n@husky.neu.edu>
Date:   Wed Feb 18 11:25:40 2015 -0800

    Merge branch 'master' into change-docs-to-biscotto

commit e4a56b3
Author: Nir Shtuhl <shtuhl.n@husky.neu.edu>
Date:   Wed Feb 18 10:13:36 2015 -0800

    update documentation to Biscotto
```

Git Town should reject the ship if the default commit message is provided.

**Comment by amohrland** [comment]
@rschifflin and I were just talking about this. Seems like this could be solved by having a hook that comments out the default message. Unless the "allow-empty-commit" flag is used, the commit will be rejected if the commit message is empty. Users will be able to see the messages from their previous commits, but will be forced to author a meaningful summary message.

**Comment by kevgo** [comment]
http://stackoverflow.com/questions/3966714/how-can-i-change-the-default-comments-in-the-git-commit-message
