### ISSUE TITLE
add style guide to CONTRIBUTING.md

### ISSUE THREAD

**Issue by allewun** [Originate/git-town#404]

**Comment by kevgo** [comment]
Do we still need this? I would be fine with "your contribution must pass our listers and match the existing style". Which is implicit. I don't want to get into the business of specifying the exact style. This would be a 10+ page exercise. We will catch a lot of the style violations in code reviews. Let's only invest the time to do this when there is an actual need, i.e. an actual problem with community contributions that are completely off.

**Comment by allewun** [comment]
:+1: sounds good
