### ISSUE TITLE
git-pr is used by git-extras

### ISSUE THREAD

**Issue by alexdavid** [Originate/git-town#413]
Can't install `git-town` and `git-extras` side by side on homebrew.

```shell
~ > brew install git-town
Linking /usr/local/Cellar/git-town/0.5...
Error: Could not symlink bin/git-pr
Target /usr/local/bin/git-pr
is a symlink belonging to git-extras. You can unlink it:
  brew unlink git-extras
```

What do you think about renaming `git pr` to `git pull-request`. It's more descriptive and I think users should decide what they want their git aliases to be, not git-town.

**Comment by kevgo** [comment]
+1 Let's rename this to `git pull-request`

**Comment by charlierudolph** [comment]
If we rename it to `git pull-request` we will clash with hub (though at least we are performing similar actions). Your argument about aliases should also apply to `git-extras`.

If we are renaming this then I suggest we also rename `git repo` to `git repository`

**Comment by kevgo** [comment]
With "clashing" you mean we do the same thing? That's one more reason to have `git pull-request` do the complete set of actions that are necessary for pull requests: sync the current branch, then start the PR.

**Comment by kevgo** [comment]
Implemented by #415

**Comment by allewun** [comment]
We're back to square one... Git Extras also has a git-pull-request!

**Comment by kevgo** [comment]
Git Extras sucks for their inconsistent command naming! Their command should be called git-checkout-pull-request. I guess by that logic we have to rename ours to git-create-pull-request then. Or git-create-pr maybe?
