### ISSUE TITLE
git prune-branches: sync all branches before pruning

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#416]
As a developer pruning branches
I want that the prune happens on the current state of the repository
So that I don't accidentally prune branches based on a stale local client.

* running `git prune-branches` on a stale local client is dangerous, because it might remove branches that have been worked on on another machine
* it is therefore necessary to always run `git sync --all` before pruning branches
* given this, `git prune-branches` should run `git sync --all` automatically

**Comment by charlierudolph** [comment]
I'm fine with not pruning a branch if its not in sync with its remote, but I would prefer not to sync every branch first. 

I also haven't used this command in a very long time am leaning towards removing it

**Comment by kevgo** [comment]
I'm happy to remove it as well.

**Comment by kevgo** [comment]
Closing this in favor of #702
