### ISSUE TITLE
add verification of file content to all feature specs

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#420]
Some feature specs don't specify the expected file content after their operation when this would be beneficial. Add those in.

**Comment by kevgo** [comment]
blocked by #422

**Comment by charlierudolph** [comment]
I'm personally against this. I don't think its necessary and with my latest drying up of file names in commit messages I want to remove file verification altogether.

**Comment by kevgo** [comment]
I don't feel strongly about this, so I'm happy to let this requirement go. Just out of curiosity, I think files having the right content after a GT operation seems kind of an important outcome to me. Are you sure that we can always assume that the file content never changes? What about the specs where the user resolves merge conflicts?

**Comment by charlierudolph** [comment]
I'd be fine leaving it in just for dealing with conflict and removing it elsewhere. If we do that we also need to make the resolve process easier to understand. Currently our resolve step is 

```cucumber
Given I resolve the conflict in "conflicting_file"
```

This hides that we resolve it by updating it to "resolved content". I'd be good with something like the following:
```cucumber
Feature: git extract: resolving conflicts between main branch and its tracking branch
  
  Background:
    # ...
    And the following commits exist in my repository
      | BRANCH  | LOCATION | MESSAGE                   | FILE NAME        | FILE CONTENT   |
      | main    | local    | conflicting local commit  | conflicting_file | local content  |
      |         | remote   | conflicting remote commit | conflicting_file | remote content |
      | feature | local    | feature commit            |                  |                |
      |         |          | refactor commit           |                  |                |
    # ...


  Scenario: continuing after resolving the conflicts
    Given I resolve the conflict by updating "conflicting_file" to "resolved content"
    # ...
    And now I have the following committed files
      | BRANCH   | NAME             | CONTENT          |
      | main     | conflicting_file | resolved content |
      | refactor | conflicting_file | resolved content |
```
If we don't supply a file name when building commits it just creates a random file, same with content.
File verification no longer checks that the list we provide is exhaustive.

**Comment by kevgo** [comment]
Sounds good!
