### ISSUE TITLE
git sync: should pull tags

### ISSUE THREAD

**Issue by retospect** [Originate/git-town#429]
When I run git sync, it should also do
git pull --tags

**Comment by kevgo** [comment]
+1

**Comment by kevgo** [comment]
[Git 1.9+](https://github.com/git/git/blob/d7aced95cd681b761468635f8d2a8b82d7ed26fd/Documentation/RelNotes/1.9.txt#L18-L20) allows to add `--tags` to `git fetch` to fetch tags. But we cannot assume Git 1.9+ everywhere. CircleCI for example still uses 1.8.6.5

Given that, I only add this to when syncing the main or a non-feature branch.

**Comment by charlierudolph** [comment]
For pre git 1.9 we can use
```
git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*
```
However the fact that we are pruning causes any local tags that have not been pushed to be deleted.
Thus I think we may need to do the pruning of deleted remote branches ourselves.

**Comment by kevgo** [comment]
We could also detect the Git version and do a separate `git pull --tags` only if the version is < 1.9. Since this is an older version, this work-around will go away once we end support for it.

**Comment by charlierudolph** [comment]
We updated git-town to require git version 2.7 or highter so we can add `--tags` to the fetch command
