### ISSUE TITLE
Add HoundCI badge

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#436]
https://houndci.com

**Comment by charlierudolph** [comment]
I personally dislike how Hound works. I don't like it commenting on your PR and would prefer it just had a status badge with a results page you can go to to view the results

**Comment by kevgo** [comment]
Yeah, the goal is to add the badge to the homepage. I think the comments are useful, given that they provide meaningful error messages, and directly help fixing them, without the user having to click around to other pages to investigate.

**Comment by kevgo** [comment]
#440 shows an example for a comment. I actually find this tremendously useful!
