### ISSUE TITLE
rename "remote" to "origin" in feature specs

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#437]

**Comment by kevgo** [comment]
blocking on #433

**Comment by charlierudolph** [comment]
Why was this closed?

**Comment by kevgo** [comment]
Sorry, I thought this was an internal ticket created by me. I tried to implement this twice, and it just doesn't feel right. It would require not only renaming `remote` to `origin`, but also renaming `remote commit` to `origin commit`, and `remote content` to `origin content`. Maybe I'm too biased here, but that feels somehow weird, and I prefer the current way. What do you think?

**Comment by charlierudolph** [comment]
Okay, I'd like to take a look since I was the one that suggested this. I'm uncertain what scope I want this to apply to.

**Comment by kevgo** [comment]
Okay, re-opened and assigned to you.

**Comment by kevgo** [comment]
@charlierudolph can this be closed, or do you want to keep working on this?
