### ISSUE TITLE
make "y" the default answer when configuring Git Town 

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#443]
When I use Git Town on a new repo, it displays this dialog:

```
Git Town hasn't been configured for this repository.
Please run 'git town config --setup'.
Would you like to do that now? [y/n]
```

It should display this:
```
....
Would you like to do that now? [Y/n]
```

Then when I press Enter, it automatically chooses "y".

Next it asks for the main dev branch. The default answer should be "master" here.

@allewun What do you think?

**Comment by allewun** [comment]
Yeah I learned about the `Y/n` / `y/N` convention after adding the prompt function. Sounds good to me!

Not sure about having the default branch as master though. I feel like it should be a conscious choice for something that impacts your whole workflow.

**Comment by kevgo** [comment]
"Default choice" doesn't mean "the right choice". It just means "what most people would type here". The purpose is to make the majority case easier. People still have to think while configuring their system. But I don't feel strongly about this, so up to you  :)

**Comment by allewun** [comment]
That's true, but I think the benefit of saving 2 seconds doesn't outweigh the user accidentally going with  "master" if that's not correct.

**Comment by kevgo** [comment]
Hmm, that argument would be true for every default value anywhere. If the user enters something wrong, she can easily re-run the setup wizard. So the (unlikely) case of an accident has a good fix.

**Comment by charlierudolph** [comment]
I'd be okay defaulting to master if we do something like `npm init` does where it shows you the default value if you just press enter

**Comment by kevgo** [comment]
Oh yeah, it should definitely display the default value, so that the user knows what she chooses.
