### ISSUE TITLE
git ship: only allow shipping approved PRs

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#445]
- scan the comments on the branch for something like `LGTM` or `:ship:`
- only perform the ship if such a comment exists
- user can override with `git ship -f`

**Comment by charlierudolph** [comment]
This requires integration with github (asking for username and password and saving an authentication token, or using their ssh key). We have quite a few other stories that are also dependent this. I'm personally against this being in this repo. I think its a good functionality but should be a plugin or something else thats not in the core of git-town.

**Comment by kevgo** [comment]
Agreed, there is a bunch of good functionality around GitHub, but it should be some sort of "GitHub plugin" for Git Town.

**Comment by charlierudolph** [comment]
Closing this as you can use protected branches and merging via the github API to accomplish this.
