### ISSUE TITLE
DRY up uncommitted file steps

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#455]
There are a million steps with `I have an uncommitted file with name: "uncommitted" and content: "stuff"`. Dry those up into `I have an uncommitted file`.

**Comment by ricmatsui** [comment]
Is it okay to have a `I don't have an uncommitted file` step that looks at a default uncommitted file name? It might be confusing since `I don't have any uncommitted files` could say there are uncommitted files. Would it be better to have a `I don't have an untracked file`? Or only dry up to `I have an uncommitted file with name: "uncommitted"`?

For example:
```
  @finishes-with-non-empty-stash
  Scenario: result
    Then it runs the Git commands
      | BRANCH   | COMMAND                             |
      | main     | git fetch --prune                   |
      |          | git stash -u                        |
      |          | git rebase origin/main              |
      |          | git checkout feature1               |
      | feature1 | git merge --no-edit origin/feature1 |
      |          | git merge --no-edit main            |
    And I get the error
      """
      To abort, run "git sync --abort".
      To continue after you have resolved the conflicts, run "git sync --continue".
      To skip the sync of the 'feature1' branch, run "git sync --skip".
      """
    And I end up on the "feature1" branch
-    And I don't have an uncommitted file with name: "uncommitted"
+    And I don't have an uncommitted file # However `conflicting_file` is an uncommitted file at this point
    And my repo has a merge in progress
```

**Comment by kevgo** [comment]
Good point! It seems we have to implement #463 first to prevent this ambiguity. 

I'm a bit hesitant to distinguish between tracked and untracked files, because there could be both in the workspace, and Git Town should handle both similarly (because of #176).
