### ISSUE TITLE
git prune branches

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#465]
Right now prune branches get rids of any branches that have been merged into master.
While this works with the flow where branches are merged into master it doesn't work very well with branches that are shipped. 

Something I been doing a lot of lately, because I have two machines, is delete branches that were shipped from the other machine. The one thing all these branches have in common is that they had an upstream branch that got deleted. 

I would like a command that deletes all the local branches whose upstream branch has been deleted. This could be a new command or simply a replacement for git-prune-branches

**Comment by kevgo** [comment]
+1 on the scenario

Right now `git sync` [re-creates deleted tracking branches](https://github.com/Originate/git-town/blob/master/features/git-sync/current_branch/feature_branch/no_conflict/deleted_tracking_branch.feature). We would have to change this behavior if we implemented this.

Couldn't we also do a `git diff main`, and if that comes up empty, consider the branch obsolete?

**Comment by charlierudolph** [comment]
Yes `git sync` recreates deleted tracking branch but you would need to run `git sync` on that branch (which I don't assume you would do if its already been shipped) or run `git sync --all`. I don't think that behavior needs to change.

I tried diffing before and couldn't get it to work. The normal diff isn't empty if master is ahead of the shipped commit, and merge diff will never be empty.

**Comment by kevgo** [comment]
I do `git sync` and `git sync --all` all the time, without thinking too much about it (when in doubt, run it), and I think that's how it should be used. 

We could try a `git merge --squash <branch-suspected-to-be-stale>` in main. If the branch is stale, the command leaves no uncommitted changes. This doesn't work in all scenarios, but in most.

**Comment by charlierudolph** [comment]
I think thats fine. I'm thinking this command would be run when you first start working on a machine that has branches you shipped from another machine (before running git sync).

**Comment by kevgo** [comment]
@charlierudolph I think only a cloud service can reliably provide this functionality. We also spoke about removing `git prune-branches`. Are you okay with closing this ticket?
