### ISSUE TITLE
git ship: add a description of the workflow how to ship to the documentation

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#479]
Several people have now accidentally shipped with the default commit message, which is almost always wrong. In addition to #382, we should also add a quick walk-through of how to ship to the documentation (man page and web).

**Comment by charlierudolph** [comment]
Fixed in f30f02ba50f8d3ff170c056de18c0eb7b0aac284 and prevented shipping with the default commit message by commenting it out in 26949dc67c245465ba2fd95a2ece3cb5cd5bece1
