### ISSUE TITLE
git ship author: same user, different email

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#485]
When git ship automatically retains the author, its leads to weird occurrences like this [example](https://github.com/Originate/git-town/commit/5bb92f2b696d2f9dcea2dba1d9dea34b15e61fca). 

This arises from accounts with two different emails. The log shows:
````
~/p/git-town> git log --format=fuller -1 5bb92f2b696d2f9dcea2dba1d9dea34b15e61fca
commit 5bb92f2b696d2f9dcea2dba1d9dea34b15e61fca
Author:     Kevin Goslar <kevin.goslar@originate.com>
AuthorDate: Mon Mar 30 21:06:54 2015 -0700
Commit:     Kevin Goslar <kevin.goslar@gmail.com>
CommitDate: Mon Mar 30 21:06:54 2015 -0700

    Update ShellCheck to 0.3.6

```

If the user is the same, but the email is different should `git ship` just not set the author?

**Comment by kevgo** [comment]
I don't understand how this could happen. I thought `git ship` creates a completely new commit, under whatever account one is logged in. Does it somehow remember who created the commits that are squash-merged?

**Comment by charlierudolph** [comment]
I implemented the feature of `git ship` retaining the author when shipping a branch [here](https://github.com/Originate/git-town/commit/00d2c2e1ed03ce46f82c3f7024127d810d9f2187).

**Comment by kevgo** [comment]
Ah, okay. Yeah, it the user account is the same, and the only difference is the email, I'm okay with just using the committing user account for now, to avoid the problem described here.

**Comment by charlierudolph** [comment]
Thinking about this more, I don't really want to support this. In the very rare case that two people have the same name but different emails addresses and are actually different people, this would be wrong. 

To avoid this as a user, simply make sure the configured user is the same on each of your machines. 

The example I pointed out could be something Github fixes anyway

**Comment by kevgo** [comment]
I don't feel strongly about this either. The current state is good enough. Its a minor annoyance at best, with indeed the chance of GitHub fixing this soon. Feel free to close this issue.
