### ISSUE TITLE
git ship: when multiple authors, allow user to select which to set as the author

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#486]
Instead of picking the author of the majority of commits, only automatically set the author if its the same for all commits, otherwise allow the user to pick which author. 

Interface could be:
* open editor to list of authors and list there commits
* user deletes the all but a single line containing the author they want to select

**Comment by kevgo** [comment]
I propose something simple like

```
Please uncomment the account for the final commit:
Jim (7 commits)
# Jack (3 commits)
# Johnny (1 commit)
```

Where the user with the most commits is pre-selected.

**Comment by charlierudolph** [comment]
Yeah I hadn't thought out the exact UI yet but something like that look great.

**Comment by alexdavid** [comment]
Why not just use stdin? That's pretty standard for stuff like this IMO.

Also I think email would be useful to display as well if one was attached to the commit
```
Choose the account for the final commit:
1. Jim S. <jim.smith@example.com> (7 commits)
2. Jack <jack@example.com>        (3 commits)
3. Johnny M.                      (1 commit)

Enter committer number (1-3): █
```

**Comment by kevgo** [comment]
Cool, a definitive +1 on showing emails. What is `stdin` though? How would we read this in bash?

**Comment by alexdavid** [comment]
You can just use `read` to read from stdin

```bash
echo -n 'Enter committer number (1-3): '
read committer

# $committer is now the users' selection
```

**Comment by kevgo** [comment]
Sounds good to me. Given that we really only need one data point here, this seems like the simplest solution.
