### ISSUE TITLE
git extract: remove dialog in favor of text editor

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#487]
I'd suggest moving to an editor where an editor is opened with the list of commits and the user deletes all but the commits they want to extract. This is similar to the git rebase interactive workflow. It removes a dependency and makes the user interface closer to the other git commands

**Comment by ricmatsui** [comment]
+1 I agree

**Comment by kevgo** [comment]
Sounds good to me

**Comment by kevgo** [comment]
This ticket is obsolete in the light of #601. Ok to close?

**Comment by charlierudolph** [comment]
Closing as git-extract has been removed
