### ISSUE TITLE
checkout with changes

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#490]
via @alexdavid 
a command that automates the following sequence:
```
git stash
git checkout
git stash pop
```

**Comment by charlierudolph** [comment]
via @alexdavid  `hot-swap`

**Comment by kevgo** [comment]
What's the purpose of this command? Doesn't `git checkout [branch] -m` do the same?

**Comment by charlierudolph** [comment]
Yeah that looks like it does it

**Comment by kevgo** [comment]
So, given that this is covered by existing functionality well enough, can we close this issue?
