### ISSUE TITLE
Change the "run_git_command/run_command" setup to "run_workspace_command/run_external_command"

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#493]
We are experiencing some technical drift as we evolve.

`run_git_command` really is now for running commands inside the user's workspace. It displays the current Git branch, because this is relevant for commands run in a Git workspace. 

`run_command` is for running stuff outside of a Git workspace, where there is not Git repo, and therefore no Git branch to show.

This situation is better described through the command names `run_workspace_command` and `run_external_command`.

Extracted from a comment in #458

**Comment by kevgo** [comment]
After talking more about this, we decided on this strategy:
* only one command `run_command` for both inside and outside workspace commits
* the arity of the data table in `Then it runs the following commands` decides whether we use a regex that captures Git branches or not. I.e. if that table contains a `BRANCH` column, we extract and verify branches, otherwise not.

**Comment by charlierudolph** [comment]
The only difference between `run_git_command` and `run_command` are whether or not we print the branch name. Thus the logic of whether or not we print the branch name still needs to be captured somewhere.

**Comment by charlierudolph** [comment]
Resolved in c40d7cfea6a9d4188bfda9610933be1f42ee1cab
