### ISSUE TITLE
CircleCI has Cabal preinstalled now

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#496]
Remove https://github.com/Originate/git-town/blob/master/bin/circleci-install-shellcheck#L7-L8

This becomes effective Apr 23, 2015

**Comment by charlierudolph** [comment]
woohoo!

**Comment by charlierudolph** [comment]
I mistook this for meaning we could just run `sudo apt-get shellcheck` which I believe is much more important as it will allow us to not have to compile shellcheck. 

We will actually still need line 8, but line 7 can be removed.

**Comment by kevgo** [comment]
Yeah, it doesn't save us much, but at least a little bit of infrastructure setup.

**Comment by kevgo** [comment]
Implemented by #510
