### ISSUE TITLE
git ship: shipping a PR from a forked repo (community contribution)

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#503]
As a repo maintainer
I want to be able to ship pull requests sent to me from forked repos by people without write access
So that I can easily manage contributions from my developer ecosystem.

* `git ship forked-account/repo-name` ships a PR from the given repo
* it is assumed that the forked account is on the same hosting service as the main repo

**Comment by charlierudolph** [comment]
@kevgo do you think this is still needed? With github's ability to now squash merge pull requests, I no longer have a need for this.

**Comment by kevgo** [comment]
Agreed. Closing.
