### ISSUE TITLE
Remove feature specs without open changes

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#506]
Initially we had different code paths for the cases with and without open changes, and needed to test both paths to achieve full test coverage. Thanks to our new command-pattern architecture, this is often no longer the case, and the feature specs with open changes are a strict superset of the the ones without open changes. 

Hence I vote to remove the test cases without open changes where it makes sense, and only keep them around if they really add test coverage. 

- [x] extract
- [x] hack
- [x] kill
- [x] new-pull-request
- [x] prune-branches
- [x] repo
- [x] ship
- [x] sync-fork
- [x] sync
- [x] town

**Comment by charlierudolph** [comment]
When we talked about this I proposed we get rid of the tests **with** open changes and if I remember correctly, thought you agreed with me. We would have some shared tests that test with open changes since that is becoming part of the framework.

**Comment by kevgo** [comment]
Clarified offline, we are going to delete the specs without open changes, because the ones with open changes cover a lot of edge cases that we might want to have properly tested (errors in the middle of what's happening etc).

**Comment by kevgo** [comment]
This is implemented now.
