### ISSUE TITLE
git-town pull-request collides with hub’s pull-request

### ISSUE THREAD

**Issue by halostatue** [Originate/git-town#507]
I use hub extensively, and prefer its pull-request to that provided by git-town (it uses the GitHub API, not the web browser). On the other hand, git-town’s version works with BitBucket.

I would suggest that a future release makes the scripts involved prefixed with `git-town`, e.g., `git-town-pull-request`.

**Comment by kevgo** [comment]
I agree. We wanted to find a better name for our pull-request feature for a while, so let's make this happen now. I propose `git create-pull-request`. Not only is this semantically more correct, it also distinguishes creating PRs from shipping them (which we also support). The users can then can git-alias this command to whatever they want, for example `git cpr`.

**Comment by charlierudolph** [comment]
I still think this and all other integration with external hosting services should be pulled out of git-town. (`git repo` and `git pull-request`). These are the only two commands that aren't an automation of a series of git commands. I'd suggest we start another project for these.

**Comment by halostatue** [comment]
I’d be OK with that, @charlierudolph. The only thing I’m using in git-town is the `pull-request` functionality—and that only for BitBucket). I don’t find the rest of the project useful for how I work.

**Comment by kevgo** [comment]
Hey @halostatue, we got #509 underway to address this ticket, and will make this change available in the next release.

Just out of curiosity, if you have some time to talk, how do you use Git, and how does Git Town not fit into your workflow? 

Our design goal is to be a generic, high-level workflow support layer for Git, which (similar to Git) works equally well for many different ways of using it. If you have a different way of using Git that isn't supported well by Git Town, I'd love to hear about it. One of our goals is adding more configurability to make GT useful to a wider audience. Thanks!  :)

**Comment by halostatue** [comment]
I use github flow. The nice thing about that is that it *doesn’t* need workflow support. It’s a matter of:

1. Make my feature branch (`git co -b feature`).
2. Work, test, repeat until done.
3. Push to GH or BB and make pull-request.
4. Code review in GH or BB.
5. Merge with GH or BB web interface. Delete the branch with same.

git-town *may* provide support for this, but it means learning more commands than I’m interested in learning, to be honest. I’m sure that the tools you’ve put together are fine and if I learned them, I might find them useful…but my workflow is so simple as to not need tools to support it, except for PR creation.

**Comment by kevgo** [comment]
Cool, thanks @halostatue. We also use GitHub Flow. Its simple and gets the job done. How big is your team? I agree that GT makes more sense for larger teams, and is overkill for smaller projects.

In a large team (5+ people), there are lots of commits on master. Then creating a feature branch isn't as simple as `git co -b feature`. You need to do run:
* git co master
* git pull
* git co -b feature

to get an up-to-date feature branch. Or you simple do `git hack feature`, which runs these steps for you. 

To avoid massive merge conflicts later, you also want to keep your feature branch in sync with the master branch, especially if the feature branch stays around a bit longer. Then you need to run
* git co master
* git pull
* git co feature
* git merge master
* git push

regularly. Or you simply type `git sync`. 

Same for shipping a finished feature branch. You want to pull updates for both the feature branch and the master branch before merging in your feature branch, to avoid conflicts later, and make sure you ship everything. You also want to delete the merged feature branch from your machine and from GitHub. Our `git ship` command does all these steps for you. 

Anyways, I'm a big fan of keeping it simple, so if your workflow works for you, that's perfect. If you ever see another dev team that is struggling with too many merge conflicts and leftover branches as they ramp up more people, tell them about Git Town!  :smiley:
