### ISSUE TITLE
Extract non-core commands that face external services into a separate project

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#512]
@charlierudolph says in #509:

> git pull-request and git-repo are fundamentally different from the rest of the commands as they integrate with external services and are not just a series of git commands.

> I believe we should move git pull-request and git repo into their own project where we introduce our own new command, call it gr (git remote) for demonstration purposes. We then have gr pull-request and gr repo and a user can do the same thing with hub and alias them to git if they want.

**Comment by charlierudolph** [comment]
`git pull-request` and `git repo` are competing in a different sector and more established realm of git tools (which is why the only clashes we've seen are with them).

Pulling them out is very straight forward. They have no dependency on the architecture we built nor use any of the configuration.

I'm happy to work on this.

**Comment by charlierudolph** [comment]
I think this should be done before the Git Town announcement as it allows us to focus on the key value Git Town provides which is the automation of git commands. `git pull-request` and `git-repo` are nice but they aren't big commands. 

We could simply remove them before the announcement to help speed things up.

**Comment by kevgo** [comment]
From my perspective:

**Pros**
* less conflicts with existing libraries (but we have solved that issue now)
* more unix-like focus for Git Town (but that's debatable, since I see GT's mission as "making Git more usable for developers", and the remote commands fit into this mission)

**Cons**
* now I have to install/update 2 separate projects that both do the same thing: making Git more usable
  * This is a higher barrier for entry and adoption
* we give away the opportunity to integrate the two types of commands forever. For example, before I create a PR, it should sync my feature branch, so that GitHub shows the latest code version, and not some earlier state. All of this should be an atomic operation, i.e. I can run `git new-pull-request --abort` and `--continue` if I run into merge conflicts here. So, `git new-pull-request` is actually a hybrid command between the two camps. Only in the current setup can we implement this appropriately.

Looking at all this together, I don't really see a strong reason to do this, but a few reasons to not do this. I'm therefore against this at this point, but open to hearing better arguments. It feels YAGNI.

**Comment by charlierudolph** [comment]
I disagree with how we have solved the issue. If hub/git-extras/some other popular git library introduces a "create-pull-request" or "new-pull-request" command are we going to rename our command again?

The separation lets us stand firm that git-town can be used in conjunction with hub and git-remote is a direct competitor with hub.

**Comment by charlierudolph** [comment]
In terms of git-town's mission, I suggest we narrow our focus. `git pull-request` is easily replaceable by `hub` and a simple Bitbucket version of something like `hub`.

Yes we lose the ability to combine higher order commands but these are fundamentally different things (seen by the extent of the `hub` library). It would be great if there are able to work together and maybe we should talk with `hub` and see if they would open to an integration.

**Comment by kevgo** [comment]
This is a tricky situation, and quite a puzzle!  :)

I'm totally with you in regards to commands like `git repo` and the upcoming [git ci](https://github.com/Originate/git-town/issues/374). I'm happy to extract them into a separate "git remote" project. 

Although that also doesn't really solve the conflict. It just moves it to another project. 

My concern is around `git new-pull-request`. I think competing directly with `hub`, i.e. providing the exact same functionality, is futile. Providing a vendor-independent version for creating pull requests has some appeal, but only to a tiny market of people who regularly work on multiple hosting platforms, and only until Bitbucket releases their own command-line tool. I have my doubts that this is enough to survive on its own. Only the GT version of this command (which also syncs the feature branch to review before kicking off the PR, and allows to resolve conflicts along the way) adds some real value in my opinion, because it goes all the way and integrates fully as a first-class citizen into the Git workflow.

Having a separate `git remote` project that follows the Git Town workflow model for remote commands seems weird to me, more like an academic distinction than a pragmatic one. If we did that, I can already hear people telling us to merge that project with GT.

I don't think we can make the `hub` project integrate with us. They'll most likely say "you should integrate with us if you want to", and be right about that. Maybe in a few years when we are the #1 tool on the market...

I don't know what we are going to do if a popular project introduces a new Git command with a conflicting name. It's a real problem that could happen for any command, and we can cross that bridge when we get there. 

It seems like the best way to go about this is to make `git new-pull-request` an optional plugin to GT. People can not install it and use `hub` or whatever, and everything is fine. Or they can install the plugin, and then have to live with whatever impacts this causes to their setup. Renaming a plugin command is easier than renaming a GT command, and doing so wouldn't affect the stability of the core GT API, thereby allowing us to get to a stable 1.0 version soon. 

This seems like the best of both worlds to me. What do you think?

**Comment by kevgo** [comment]
Implementation of this plugin system would be super easy:

We provide all commands including plugins in the normal GT install. Commands are in the folder `src`, which is in the path, meaning these commands are available to the user. Plugins are in the folder `plugins`, which is not in the path, meaning these commands are not available. This setup makes it easy to code/test plugins using our existing helper and testing infrastructure. 

All we need then is the ability to selectively activate/deactive certain plugins. 
* When the user runs `git town activate new-pull-request`, it simply copies the `git-new-pull-request` shell script from the `plugins` folder into the `src` folder. It is then available as a normal Git Town command.
* When the user runs `git town deactivate new-pull-request`, it deletes the `git-new-pull-request` shell script from the `src` folder.

**Comment by charlierudolph** [comment]
That sounds like it would work for manual installs but not for installations via homebrew where each  command is symlinked by Homebrew into the `/usr/local/bin`

**Comment by allewun** [comment]
This is an interesting conversation. I don't have a strong opinion on this yet, but I think I'm slightly favoring @charlierudolph's side.

The fact about the 2 commands not relying on any of the underlying GT infrastructure is a pretty good indicator that they're auxiliary commands. One minor pain point I've run into: for any repo I quickly clone and poke around with, when I run `git repo`, GT will ask me to configure it. For my purposes this is extra unneeded friction.

Perhaps just pulling these scripts out into separate projects might suffice? `git repo` was originally just a function I wrote/modified for myself before it was introduced into GT. For those that only want this simple piece of functionality, the entire GT suite is a lot of undesired overhead.

Then we could have `brew install git-repo` available after tapping `Originate/gittown`. We will get "plugins" for free in this case.

**Comment by kevgo** [comment]
If it were for the current state of the code base, I would agree with the proposed idea here, extract `git repo`, `git pr`, and `git ci`, and move on. 

The problem is, we have a whole set of commands on our roadmap that are "hybrids" between the two proposed repos:

* [git ship: use the title of the associated PR for the commit message](https://github.com/Originate/git-town/issues/148)
* [git ship: add "closes #[PR number]" to the description of shipped branches](https://github.com/Originate/git-town/issues/51)
* [git pr: should push branch if necessary](https://github.com/Originate/git-town/issues/367)
* [git ship: only allow shipping approved PRs](https://github.com/Originate/git-town/issues/445)
* [git ship --green (more robust shipping process)](https://github.com/Originate/git-town/issues/201)

All of these features are useful, reduce boilerplate, and make developer lives better. So I want them to happen. They also mix the proposed core GT functionality (to remain in git-town) with vendor-specific functionality (to extract into git-remote, gt-github, or whatever). These features are trivial to implement in the current setup, and hard after the proposed separation. 

From that perspective, the proposed separation tries to solve a minor annoyance (possible future naming conflicts), without even solving it (we just move the problem to another repo and still have it there, and any of the remaining GT commands can still have naming conflicts). It comes at the cost of introducing a significant architectural roadblock and headache (separation into two repos), a lot of extra infrastructure in the code base (plugin mechanism), as well as more overhead and complexity for our users: they have to get educated about that there are two projects, what their difference is, decide which ones to install, then install several things and work out interoperability issue for their particular setup (like what happens if I update GT but not the plugins, or vice versa). 

That's my concern here. If we figure these issues out, I'm happy to do this split.

**Comment by kevgo** [comment]
Another route we could go, one that solves all these issues for good, once and for all, is what the `hub` project does. They provide their own command (hub), and its up to the user to alias it to `git`.

In a similar fashion, we could provide a `gt` command. This gives us own namespace for commands, and we can do whatever we want to do here. Git Town runs fine next to hub, git-extras, and anything else, as long as the user doesn't alias anything. If the user wants to alias any of those commands to `git`, its up to her to make sure there are no collisions. `gt` is also shorter than `git`.

Type `hub alias` to see how this works for hub.

What do you think?

**Comment by ricmatsui** [comment]
I think that providing a separate command like `gt` or `town` similar to `hub` makes a lot of sense and the method for aliasing all the commands like `eval "$(hub alias -s)"` feels pretty standard to me, too. I think it helps meet in the middle while keeping it simple, and lets the user pick and choose the commands if they want to use multiple `git` tools.

**Comment by kevgo** [comment]
I think we have agreement to move forward with #515 instead of this. Closing.
