### ISSUE TITLE
throttling fetches

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#513]
Almost every GT command does a `git fetch`. When using a lot of GT commands consecutively, this can cause a lot of fetches, each one causing a delay and extra network traffic.

To alleviate this, we could introduce a minimum time between fetches. Let's say it is set so that a fetch can only happen every minute. If I run 3 GT commands consecutively, only the first one would do a fetch. The remaining two commands would skip the fetch phase, since there was already a fetch (in the first command) less than a minute ago.

This could be implemented relatively easy by storing the unix time stamp of the last fetch in the GT metadata.

**Comment by charlierudolph** [comment]
I'm on the fence about this. If someone else committed while you're throttled you have to wait.

**Comment by kevgo** [comment]
Yeah, it might be premature optimization, which can introduce side effects. Closing.
