### ISSUE TITLE
git-hack fails when run in new directory

### ISSUE THREAD

**Issue by allewun** [Originate/git-town#514]
Similar to #371. I forgot where I was in the folder hierarchy when I ran git hack (was on a feature branch that added new subdirectories).

**Comment by kevgo** [comment]
As discussed in #501, I think we need to provide a command-independent layer in the GT framework to support for this in a DRY fashion on all commands that change branches.

**Comment by kevgo** [comment]
@charlierudolph I think this ticket can be closed now, given your new architecture that moves cd-ing into the Git root into the framework.

**Comment by charlierudolph** [comment]
Its part of the framework but its opt-in and currently git-sync is the only command thats opts in.

**Comment by kevgo** [comment]
Resolved by https://github.com/Originate/git-town/commit/94e5114e7acf695cb57f89e193bb34ddaaf1ae47
