### ISSUE TITLE
Create a separate command-line executable for Git Town

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#515]
Create a `gt` or `town` command-line tool to run the Git Town commands. Similar to [hub](https://github.com/github/hub), this tool can be aliased to `git` if needed.

Advantages are
* Git Town becomes completely independent from any other Git tool or plugin in the world
* Git Town commands can still be made Git commands by aliasing the tool
* resolving naming conflicts in user's setup becomes a responsibility of the user

This idea came out of #512 and #509.

**Comment by charlierudolph** [comment]
:+1: this would be very good to have. May need to implement out own command redirection as git takes care of the automatically running `git-ship` when we run `git ship`.

If we were to name it `town`, we may need to rename `git-town` command which would be run with `town town` if it hasn't been aliased.

**Comment by kevgo** [comment]
Yeah, I think we would have to rename `git-ship` to `gt-ship` or something as part of this.
