### ISSUE TITLE
Separate `push_branch` into two commands 

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#519]
Our `push_branch` helper currently does two different things, depending on context:
* it creates a new remote tracking branch
* it pushes to an existing remote tracking branch

These commands are implemented through different Git commands, and they are undone in different ways. Its therefore better to separate them into different commands:
* `create_tracking_branch`
* `push_branch`

This will allow to undo pushing branches more precisely, and thereby allow to undo commands like renaming branches.

**Comment by charlierudolph** [comment]
Can you point to where this takes place? I don't think this done with two separate git commands as the `-u` option to git push is what we are using to set the upstream branch. We can certainly break this into two commands which would make undoing the initial push of a branch unset the upstream.

**Comment by kevgo** [comment]
Yes, this would require to change the way we push branches, and do pushing and creating the upstream as two separate operations instead of a single `git push -u`.

**Comment by kevgo** [comment]
This is also a prerequisite for proper undoing of #664
