### ISSUE TITLE
Support for nested feature branches

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#529]
> As a user working on a feature that depends on another feature currently under review
I want to be able to cut feature branches off other feature branches and sync them properly
So that my development pace is not slowed down by having to wait until the features that my new features depend on ship.

* [x] `git hack my-feature dependent-feature` cuts the `my-feature` branch off the `dependent-feature` branch, not the main branch
* [x] `git sync dependent-feature` first merges the main branch into the `dependent-feature` branch, then the `dependent-feature` branch into the `my-feature` branch.
* [x] `git ship dependent-feature` ships the given branch, then adjusts all dependent branches like `my-feature` to be cut directly off the main branch
* [x] `git rename-branch dependent-feature` properly updates the branch name in the dependency list
* [x] `git new-pull-request` sets the branch to merge into to `dependent-feature` instead of main
* [x] `git-prune-branches` removes pruned branches from the branch hierarchy
* [x] `git-kill` points child branches of the killed branch to the parent of the killed branch

**Comment by kevgo** [comment]
We want to provide a robust and safe solution for our branching model:
* don't allow shipping branches which depend on unshipped branches
* when shipping a branch that has dependent branches, update the dependent branches to be dependent on main now.
* sync branches in the order in which they were cut

In order to achieve that, we need to know the exact hierarchy of branches.

**Comment by kevgo** [comment]
Preliminary research indicates that Git treats all branches as equal: branch A can be seen as cut from branch B, or vice versa. In our branching model feature branches are not equal. If feature branch B is cut from feature branch A, this relationship is not reciprocal, i.e. feature branch A shouldn't be seen as cut from feature branch B. 

`git reflog -g <branch-name> | grep 'branch: Created from' | cut -d ' ' -f 6` sometimes prints the name of the branch from which the given branch was cut. Sometimes it just prints `HEAD` though, which isn't helpful. 
Also, the reflog seems only available on the local machine, and it only spans a certain number of days before it gets garbage collected.

Git does therefore not reliably provide the needed exact and reliable hierarchy of branches. 
Achieving this seems only possible if we keep a dedicated log of that information on our side.

**Comment by kevgo** [comment]
Currently, the branch hierarchy list needs to answer the following questions: 
* what is the parent for branch X?
* what are the dependents branches for branch X?

We have discussed two ways to implement our branch hierarchy list:

1. create a new orphaned branch called `gt-data` (or something similar) that contains files which describe the branch hierarchy list.
  * can answer all questions
  * is flexible and extensible
  * can be added/removed at any time
  * can be augmented with information queried from the user
  * format can be changed over time
  * but introduces a new branch, which pollutes branch lists

2. create intermediate commits that encode this information in their name
  * Git resolves all hierarchy information for us
  * can not answer easily which branches depend on the given branch
  * if there is ever a single non-squash commit, the commit history on main is forever tainted with an old commit
  * impossible to update the storage format for older entries

(2) seems to have too many shortcomings, so (1) seems the way to go.

**Comment by kevgo** [comment]
After talking more about this:

* we are building a cache of information about which branch has which other branch as a parent. In the case that branches `f1` and `f2` are cut from main, and `f3` is cut from `f2`, this cache would look like:
  ```
  f1: main
  f2: main
  f3: f2
  ```

  Querying this cache can be done through grepping for `<branchname>:` for branches that were cut from our branch, and `: .* <branchname>` for the branch that our branch was cut from.

* the cache is automatically populated through `git hack <branchname> <parent-branchname>`

* if cache information isn't available, we query the user for the branch hierarchy. We can do an number of analytics to infer the "most likely correct" branch setup, but the user should confirm it.

**Comment by ricmatsui** [comment]
This would be very useful!

What do you think of when running `git sync dependent-feature` having `my-feature` not change? Then running `git sync my-feature` will sync `my-feature` with `dependent-feature`. It might make more sense if another developer also has a branch cut from `dependent-feature` and also deeper trees of dependencies.

I think the cache design will also be good for storing the configuration including the main branch and perennial branches. Maybe configuring git town would simply be creating the orphan branch and putting the configuration there.

**Comment by kevgo** [comment]
This feature is implemented.
