### ISSUE TITLE
GitHub-compatible squash-merging

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#530]
GitHub doesn't understand when branches are squash-merged. It simply shows that the branch was closed. Git Town's GitHub extension should add a comment into the PR saying something like `[username] merged this into [branchname] as [sha]` before doing the ship. This creates a connection between the PR and the commit it lead to.

**Comment by ricmatsui** [comment]
What do you think of also adding a `squash-merged` label to the PR to make it easier to see that the PR was merged in the list view, since the PR would still have the red closed icon rather than the purple merged icon?

**Comment by kevgo** [comment]
Interesting idea. I can see this being helpful for some teams. Since this would require such a label to exist on GitHub, and interfere with the respective team's labeling system, it should be optional in my opinion. Like with all optional things that add complexity, let's wait for real demand that outweighs the extra complexity before adding this in.

**Comment by kevgo** [comment]
This is obsolete since the PR can be mentioned in the commit, thereby creating this connection.
