### ISSUE TITLE
Protecting the primary branch

### ISSUE THREAD

**Issue by alexpeachey** [Originate/git-town#539]
Would it make sense to try and warn/restrict people from direct interaction with the primary branch?
I'm not sure what's possible or not with the git enhancements, but if someone using git town tried to commit directly on the primary branch, if it could be caught and a warning shown, with the option to force, that would be nice.

Someone wasn't paying enough attention and committed to the primary branch and then did `git sync` and is now reverting and cleaning up the mess.

**Comment by charlierudolph** [comment]
Hmm. I've actually ran into this a few times too. One way we could handle this could be when syncing the main branch if git town sees that the local main branch is ahead of the remote main branch, it pauses and prompts the user who can confirm and continue or abort.

**Comment by alexpeachey** [comment]
Yeah, that might be a good way to handle it. If there is a problem and it was a mistake they can take care of the reversion locally before it pollutes the shared state.
And since it's just dealing with the `sync` command git town has full control. So yeah, I'd love to see that added.

**Comment by kevgo** [comment]
I'm ambivalent on this. 

On one hand :+1: on protecting shared state from being polluted by mistakes, through warning if direct commits into main are pushed. 

On the other hand, are we sure that direct commits into master are always a bad thing? What about a tiny syntax fix? Do we want to force people to create feature branches even for that? I'd rather not be so heavy-handed here. One of the advantages of GT (that I want to maintain) is that it is non-intrusive. Anybody can keep using Git the way they want, and are used to. GT makes it easier to use Git correctly for "typical" feature development, by automating some of the steps typically done here. But without forcing our users into a particular way of doing things, or to always having to use our automation. 

Also, the proposed feature would show irritating warnings for legit use cases. Lets say I work offline (for example on a plane). I create a feature branch and then ship it. This creates a local commit on master that is legit, but looks not legit according to the verifications proposed here. When I then run `git sync`, it would then show the warning proposed here, and force me to override GT's opinion through a forced push, even though I used it correctly. This can quickly lead to frustration, seeing GT as fragile and annoying, and even worse forming habits to distrust GT warnings, ignoring them, and force-pushing one's way through life. That's a problem. 

So unless we can find a way to make this feature more bulletproof, I'm against it, even though it is useful in many situations. We could log all properly shipped commits somewhere, and provide configuration options to apply these verifications to certain users (like junior devs) only. But all of that adds a lot of complexity, which impacts maintainability and learning curve for users.

**Comment by charlierudolph** [comment]
I don't like the idea of warnings. I'd suggest it prompts for confirmation to make sure you know what you're doing. Users could then also turn this confirmation off for their repo if they want. I dislike the idea of using a force flag.

@kevgo How often do you ship a feature branch while offline? Personally never done that. I've created and worked on feature branches, but never shipped them while offline. That sounds like thats a personal repo to me and I think adding in an option that allows you turn this confirmation off for specific repos could solve it.

**Comment by kevgo** [comment]
Yeah, to be honest I don't do that much as well, but ship when online. So I guess I'm okay with showing a confirmation, as long as there is an option to disable this feature.

**Comment by alexpeachey** [comment]
I like the idea of confirmation with a config option to turn that off if you don't like it. I also think this applies only to git town commands. (i.e. git sync, git ship, etc) when on the main branch. It's unlikely this is what you actually want to do. If you do want to just "slip something in" like a minor fix in the example scenario, then why not just commit and `git push`?

So overall I'm all for the confirmation and have no problem giving a config option to turn it off. If someone wants to turn it off because they regularly do a non-standard thing and the confirmation warnings are annoying then sure, let them.

**Comment by kevgo** [comment]
Cool, sounds like we have agreement on this!

**Comment by arekkas** [comment]
👍 from me because I accidentally pushed directly to master with `git new-pull-request`

**Comment by kevgo** [comment]
This can be achieved using GitHub features now that we can ship via the Github API. Closing.
