### ISSUE TITLE
git ship -f

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#583]
As a user getting an error that I cannot ship a branch for some reason
I want to have a way to ship it anyways despite what my local Git Town client thinks
So that Git Town doesn't get in my way.

**Comment by charlierudolph** [comment]
What is an example of the reason you are prevented from shipping?
I'm fine with using `-f` for overriding very specific and documented examples, but not just anything.

**Comment by kevgo** [comment]
Good point. Closing for now until we have good reasons to do this.
