### ISSUE TITLE
Add Twitter icon to web site

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#587]
Link to https://twitter.com/GitTown

**Comment by charlierudolph** [comment]
There is an "Ask a question" button at the end of the FAQ that links there

**Comment by kevgo** [comment]
True. I think if we use Twitter, we need a more official logo for it (with the birdie), and it should be more prominent.

**Comment by redouglas** [comment]
see PR #627 Is this what you wanted @kevgo ?

**Comment by kevgo** [comment]
As discussed in person today, this is cool, and lets also try to add a Twitter logo somewhere above the fold.

**Comment by charlierudolph** [comment]
Fixed in 4c59b2d8c884801582fbecedb1e378c821157a97
