### ISSUE TITLE
Create logo with font vertically centered and a bit smaller (for homepage)

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#588]
The current logo has the font aligned with the bottom. It would be better to have the text horizontally centered.

**Comment by redouglas** [comment]
It should probably stay that way - we just need to offset the logo such that the baseline of the logo text (imaginary line that the text was 'written' on) is inline with the baseline of the menu item text

**Comment by kevgo** [comment]
Okay, adjusted on the life site. Please take another look. Whatever you decide is fine with me here - as long as it doesn't offend by taste buds!  :)

**Comment by redouglas** [comment]
Adjusting dimensions as per #586
