### ISSUE TITLE
remove changelog

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#594]
Instead just put the release notes [here](https://github.com/Originate/git-town/releases)

**Comment by kevgo** [comment]
Hmm, then we are forever bound to GitHub, and the release notes are no longer in a searchable/greppable format that is available together with the source code offline. I can see its nice to get rid of a file, but there are a few too many drawbacks. Not feeling strong about it though, so if others think this is a good idea, I could get behind it.

**Comment by charlierudolph** [comment]
This is something done by [chai](https://github.com/chaijs/chai). So wanted to bring up the possibility. Yeah I guess searching it is nice and locking us into Github does suck a bit (though I doubt we will leave anytime soon). Closing...
