### ISSUE TITLE
git new-pull-request/repo prints unnecessary newline 

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#602]
In 0.7
```
> git pr

> git repo

> 
```

Believe this was caused by the fact that each now uses the step architecture when they don't need to. Introduced in 380a2ccb3e3f89c14ec8ee2f570ad5927a83918c

**Comment by kevgo** [comment]
Is this an issue? I actually prefer a little visual separation between commands.

**Comment by charlierudolph** [comment]
I prefer what it was before which was
```
> git pr
> git repo
> 
```
At the moment I also don't see any reason to use the step architecture as these run a single command.

**Comment by kevgo** [comment]
Okay, cool with me
