### ISSUE TITLE
git sync --all

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#604]
If a feature branch does not have its parent branch configured, it only merges its own remote.

**Comment by kevgo** [comment]
Isn't that what its supposed to do? I guess we could also ask for the parent right there, is that what you intend it to do here?

**Comment by charlierudolph** [comment]
Before 0.7, my branches were automatically merging in the main branch. They no longer are.

Yes I suggest `git sync --all` ensures each branch has a parent branch. Running git sync on a single branch asks for the parent branch if its not there.

**Comment by kevgo** [comment]
Makes sense.
