### ISSUE TITLE
git town doesn't handle forward slashes well

### ISSUE THREAD

**Issue by dougvk** [Originate/git-town#608]
if I `git hack dvk/feature-name` git town breaks. it needs to be `git hack dvk-feature-name`. either way, at least give a better error message to the user.

**Comment by charlierudolph** [comment]
Thanks for reporting this. 
In the future please include the error, as I have done below
```
> git hack cr/test
[master] git fetch --prune

[master] git rebase origin/master
Current branch master is up to date.

[master] git checkout -b cr/test master
Switched to a new branch 'cr/test'
error: invalid key: git-town.branches.parent.cr/test

To abort, run "git hack --abort".
To continue after you have resolved the conflicts, run "git hack --continue".

```

**Comment by dougvk** [comment]
thanks and sorry, will do

**Comment by allewun** [comment]
Interesting, it works for me. What version of git are you guys using? I'm on 2.4.2

**Comment by allewun** [comment]
Nevermind about the git version. Tracked it down to this commit that introduced the issue: 252fd3c2
