### ISSUE TITLE
Save previous branch

### ISSUE THREAD

**Issue by allewun** [Originate/git-town#65]
I frequently use `git checkout -` to switch to a previous branch.

Scenario:
* Currently on feature branch `A`
* Checkout another feature branch: `git checkout B`
* `git ship`
* After shipping, current branch will be `<main_branch_name>`
* I'd expect `git checkout -` to take me to `A` at this point. In actuality, git is trying to take me to the true previous branch, which is B (which has just been shipped and deleted).

Since `git ship` feels like an atomic operation, I'm frequently wanting to go back to the original branch I was on before shipping. Does this issue make sense?

**Comment by allewun** [comment]
I think I'd still like this.

```bash
foo$ git hack bar
bar$ git checkout -
master$
```

Would like to end up on `foo` and not `master`.

**Comment by charlierudolph** [comment]
Is there a command that lets you view the checkout history? Anyway we can edit that? (or have our checkouts not add to it). Otherwise I assume we just need to tack on a couple extras checkouts right? Should we display these or not? (they aren't important in the workflow and are just returning the state).

Also do we only need this for commands that end on a new branch (hack and extract) as oppose to all? sync stays on the same, kill/ship delete the current branch or stay on the same branch (when branch name provided).

**Comment by allewun** [comment]
> Is there a command that lets you view the checkout history?...

I haven't found a command for this (or even a plumbing command), but there's a way you can view the complete history of all checkouts in a repo: `.git/logs/HEAD`

I think touching the file directly is probably not a good idea. I'm leaning towards having another temp file to track this.

> Also do we only need this for commands that end on a new branch...

And that's up for discussion as well. I'd say commands that change branches are more important that those that don't. But having checkout atomicity for all git town commands would be nice to have eventually.

**Comment by charlierudolph** [comment]
:+1: now in full support. Just changed branches, made a change and synced, and want to go back now and can't.

**Comment by kevgo** [comment]
An easy and robust (but rather primitive) solution to build this would be:
* stash away open changes
* determine the previous Git branch and store it in a variable
* run the Git Town logic
* checkout the previous branch
* checkout the current branch
* pop the stash

This puts the previous branch back into the Git history. Given that the open changes are stashed away, this should be clean, without conflicts.

**Comment by kevgo** [comment]
@allewun I remember some work on this a while ago. Did we end up implementing this?

**Comment by allewun** [comment]
I had a partial implementation (#501) that got left behind as the architecture changed. I'm planning to tackle this again now that the architecture has stabilized.
