### ISSUE TITLE
Add repo-command support for GitHub Enterprise.

### ISSUE THREAD

**Issue by pedramamini** [Originate/git-town#654]
Make `git repo` work in GHE environments.

**Comment by kevgo** [comment]
Definitely! Can you please post the output of running `git remote -v` in a Git repo that uses GHE?

**Comment by lethjakman** [comment]
I want this same feature! 

My git remote -v

```
upstream	git@github.my-company.com:my-company/my_repo.git (fetch)
upstream	git@github.my-company.com:my-company/my_repo.git (push)
```

**Comment by kevgo** [comment]
Thanks! So it seems there is no way of recognizing whether a git remote is powered by GHE or some other software, and we have to add a configuration setting that allows GHE users to enable GitHub compatibility.

**Comment by lethjakman** [comment]
It seems to me that a regex could be run against the remote url to check if
it's github.com or not? However, I do know a lot of other software uses
configuration for enterprise.

**Comment by kevgo** [comment]
I read through the documentation for GHE, and it seems like the URL doesn't have to contain "github".

**Comment by charlierudolph** [comment]
Going to close this due to age. We are happy to support something like this, but ideally someone who uses this would implement it as then they can test it locally and ensure its working. I'm happy to provide assistance.
