### ISSUE TITLE
--dry-run command-line switch

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#659]
When given, the commands only show the Git commands that they would run, but don't execute them.

**Comment by soenkehahn** [comment]
This would especially be useful when starting to use `git-town`. I'm a bit hesitant to run `git-kill` before seeing what it'd actually do.

**Comment by charlierudolph** [comment]
To me this would add too much complexity to be worth it. I'd prefer just updating the documentation with an example of the commands that will be run (or possibly point to a feature test where it already does).

**Comment by allewun** [comment]
I think this is a worthwhile feature. Most of my work on git-town was to make it more accessible to users, and I think this falls nicely into that mission. Given how much power the commands offer, being able to do a dry-ran can be invaluable for new users.

Whether or not the complexity is overwhelming is still up for debate.

**Comment by kevgo** [comment]
I think this is already implemented. Closing.
