### ISSUE TITLE
better documentation for commands

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#660]
- move command documentation from GitHub to the web site
- add screen shots of terminal output

**Comment by atilacamurca** [comment]
How do you guys plan to do this issue?

You have the `/website` directory and the command documentation is in `/documentation/commands`, so what's the plan? Symbolic links or move the documentation to `/website`?

**Comment by waldyrious** [comment]
@kevgo, for future reference, can you indicate why this was closed? Was the plan abandoned or replaced by something else (perhaps #684)?

**Comment by kevgo** [comment]
Hey @waldyrious, we found that the current documentation on Github turned out sufficient for the current state of the product. Git Town is a developer-facing tool, and developers are familiar with reading documentation on Github. The website is at this point just a lightweight entry point to get people started, that's why it leads them over to Github. #684 is a good idea that we might do in the future, but we don't have the bandwidth to do it right now.

**Comment by waldyrious** [comment]
Ok, thanks for clarifying 👍
