### ISSUE TITLE
Verify that commit message links to PR

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#662]
Squash merging requires to link to the shipped PR in the commit message. If that is missing, git-ship should confirm from the user that it is okay to ship without that link.

**Comment by charlierudolph** [comment]
:+1: After the commit we can add a step to verify what the last commit message was and prompt the user to continue, abort, or amend the message

**Comment by kevgo** [comment]
One possible solution according to @charlierudolph:
* in `git-ship`, perform the commit
* check the commit message of the last commit
* if it lacks the mention of the PR, show an error, and make another commit that amends the previous commit

**Comment by charlierudolph** [comment]
Closing since we can now merge with the Github API and the link is then automatic and doesn't need to be referenced in the commit.
