### ISSUE TITLE
git-hack: create the new feature branch as the parent of the current branch

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#665]
As a user working on a feature X and realizing my feature is dependent on a separate change ("feature W") to be made first
I want to be able to create a new feature branch W as a parent of my existing branch X
So that I can implement feature W, and once that's in review keep working feature X without having to wait until feature W is shipped.

**Comment by charlierudolph** [comment]
@kevgo closing this as it and #766 appear to be duplicates and #766 has a feature attached.

**Comment by kevgo** [comment]
Good catch, I didn't realize we were talking about this before
