### ISSUE TITLE
`git town config --setup` doesn't do anything if git town is already configured

### ISSUE THREAD

**Issue by allewun** [Originate/git-town#674]

**Comment by charlierudolph** [comment]
What should it do?

**Comment by allewun** [comment]
I thought it used to just take you to the configuration. Maybe we should show a message like:

> You've already configured Git Town for this repository. If you'd like to reconfigure it entirely, please run `git town config --reset` first.

**Comment by charlierudolph** [comment]
It used to prompt you for information, thus overwriting your existing configuration. 
I think outputting nothing is expected.
Maybe we should just update the description 
```
With the `--setup` flag, prompts the user for any missing Git Town configuration
```

**Comment by allewun** [comment]
Yeah I misspoke, I meant it used to take you to the prompt. Do we not want that behavior anymore?

**Comment by charlierudolph** [comment]
Personally no. How about `--reset` clears out the old information and prompts you immediately?

**Comment by kevgo** [comment]
I think `--setup` should always run through the setup wizard (with existing values as defaults).


We can then get rid of `--reset`. What's the point of running reset? Only to run setup right after it again. Reset doesn't make sense by itself, so it has no reason to exist.

Then only reason to delete configuration data is when uninstalling GT. That should be done by an `implode` or `uninstall` command.

**Comment by allewun** [comment]
> I think --setup should always run through the setup wizard (with existing values as defaults).

I agree

> We can then get rid of --reset. What's the point of running reset? Only to run setup right after it again. Reset doesn't make sense by itself, so it has no reason to exist.
>
> Then only reason to delete configuration data is when uninstalling GT. That should be done by an implode or uninstall command.

I think `--reset` should be kept with its current behavior. If users don't want to use GT anymore (could be on a per-repo basis), they shouldn't be forced to have stray metadata sitting around. Uninstalling GT globally can't automatically delete GT config data on every repo on a user's machine.

**Comment by charlierudolph** [comment]
Okay. I'm fine with --setup taking you through the wizard. I only converted it because I wanted the prompt when running other commands to only prompt for the missing information.
