### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by allewun** [Originate/git-town#677]
- `--undo` is not documented for `git-hack`, `git-prune-branches`, `git-ship`, `git-sync`
- `git-prune-branches` could use some more documentation

**Comment by kevgo** [comment]
Missing features specs for undo: `git-hack`, `git-sync`

I think we are contemplating about getting rid of `git-prune-branches`, since it doesn't do anything useful right now.

**Comment by allewun** [comment]
Wasn't there also some discussion about removing `git-extract`?

**Comment by kevgo** [comment]
Yes, #601 tracks this.

**Comment by charlierudolph** [comment]
* `git hack` and `git sync` no longer have undo options
* `git prune-branches` and `git ship` do need to have their documentation updated

**Comment by kevgo** [comment]
Closing this since commands no longer have undo options, and we are now verifying the correct documentation via Text-Runner.
