### ISSUE TITLE
Undo commands not found

### ISSUE THREAD

**Issue by atilacamurca** [Originate/git-town#678]
When I execute git sync, the undo commands are not found.

Output excerpt:

~~~
/usr/local/git-town/src/helpers/undo_helpers.sh: line 35: post_undo_steps_for_stash_open_changes: command not found
/usr/local/git-town/src/helpers/undo_helpers.sh: line 35: post_undo_steps_for_checkout: command not found
/usr/local/git-town/src/helpers/undo_helpers.sh: line 35: undo_steps_for_rebase_tracking_branch: command not found
~~~

OS:
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

git version 1.9.1
Git Town 0.7.3 (20 Sep 2015, 2b77a8e)
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)

echo $PATH
`/usr/local/git-town/src/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

**Comment by kevgo** [comment]
Thanks for the bug report! I assume that the rest of the functionality, i.e. running `git sync` normally, works for you?

**Comment by atilacamurca** [comment]
Yes, the sync and the other commands works just fine. But the messages about the command not found keep showing. I assume that if a command failed it cannot be undone.

**Comment by atilacamurca** [comment]
I think I found the cause of the error.

In line 35 of `src/helpers/undo_helpers.sh` we have:

~~~
if [ "$(type "$fn" 2>&1 | grep -c 'not found')" = 0 ]; then
    eval "$fn $arguments"
  fi
~~~

My system is in Brazilian Portuguese and the `grep` command tries to search for an English
phrase `not found` (in my case is the string `não encontrado`).

PS: I post the issue as my output was in English but is actually in Brazilian Portuguese, sorry :)
