### ISSUE TITLE
git-new-pull-request for forked repos

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#682]
The introduction of nested feature branches took away a nice feature of git-new-pull-request with forked repos. 

Github was assuming a pull request for a branch would always be made against the master of the fork and was redirecting you there. Now that we specify the parent branch this has gone away.

What do you think about the Github version of new-pull-request not specifying the parent branch if it is equal to the main branch?

**Comment by kevgo** [comment]
SGTM
