### ISSUE TITLE
Hot fix branch support

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#690]
**context**
Let's assume a setup where `development` is the main branch, and `production` is a perennial branch. A _hot fix branch_ is one that is made directly off `production`, and after LGTM is merged straight back into production. 

**expected behavior**
`git ship` should do the merge into production, and then ask whether the branch should also be merged into the main branch.

**actual behavior**
Currently `git ship` shows an error message that `production` should be shipped first (which makes no sense since it is a perennial branch).

**Comment by charlierudolph** [comment]
How about just opening up the idea of shipping to branches other then main? What wrong with just always shipping into the parent branch?

**Comment by kevgo** [comment]
I have seen developers trying to do this a number of times, but it was always a result of broken processes and based on not understanding how Git works, and shouldn't have happened.

- if you ship into another long-lived branch (like a bigger feature branch), make it perennial and sync it regularly.
- if you ship into another short-lived feature branch, these changes have to be reviewed again. This is inefficient. So unless I hear about a useful scenario, I consider this is an anti-pattern.

**Comment by kevgo** [comment]
Fix: git ship should recognize if the branch shipped into is perennial and ship anyways

**Comment by charlierudolph** [comment]
Going with close as with 4.2.0 you can now ship into perennial branches
