### ISSUE TITLE
`set -e` missing from `helpers.sh`

### ISSUE THREAD

**Issue by twolfson** [Originate/git-town#693]
I was perusing the source code and noticed that there is no `set -e` being invoked with respect to any of the scripts in `src/`. I saw a mention of using a `set -e` in `src/helpers/helpers.sh` but the actual line 
seems to be gone =/

https://github.com/Originate/git-town/blob/v0.9.0/src/helpers/helpers.sh

I was wondering if that was intentional. If not, I would be more than happy to add one back.

**Comment by kevgo** [comment]
Thanks for the request! Our scripts run commands which can return non-zero exit codes as part of normal operations. For example, trying to read Git configuration that doesn't exist (which is valid) causes `git config` to exit with status code 1. As a result, our commands cannot automatically error out on every failure. 

We carefully check for errors, though, and have a very comprehensive test suite to cover all important cases. 

We are open to ideas on how to do this better and/or more in line with Bash, however!  :)

**Comment by twolfson** [comment]
While it's good to not exit on one-offs like `git config`, it leaves the script open to continuing to run after commands unexpectedly fail. No matter how good your test suite is, this will happen -- e.g. what if a user has super old version of `git`, `bash`, or maybe they are on OS X and have older `coreutils`.

If a command is known to occasionally fail (e.g. `git config`), I can think of a few options:

- Toggle `set -e` on/off around that line

```bash
set +e
user_name="$(git config --get user.name)"
set -e
```

- Use `|| true` to allow the line to fail

```bash
user_name="$(git config --get user.name || true)"
```

- Define a helper that invokes the command and allows for failure

```bash
safe_exec () {
  $* || true
}
user_name="$(safe_exec git config --get user.name)"
```

**Comment by kevgo** [comment]
Very cool ideas, thanks! I like the idea of a `safe_exec` method that runs commands and ignores their error codes. This would indeed allow us to fail fast on errors, which I agree in better to have than to not have it.

**Comment by kevgo** [comment]
Hey @twolfson, if you want to send a PR adding better error checking, it would be appreciated!

**Comment by twolfson** [comment]
I am not going to be free to take a look at this within the next week but I will let you know when I do.

**Comment by twolfson** [comment]
Sorry, I finally got back and am feeling overwhelmed with other priorities. I don't think I will be able to look at this any time soon.

**Comment by kevgo** [comment]
Obsolete with the Go rewrite
