### ISSUE TITLE
Git config: should not verify that perennial branches exist

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#698]
I was setting up a new instance of Git Town. The setup asked me for perennial branches. I told it `gh-pages`. It complained that there is no such branch. This is wrong on 2 levels:
* that branch exists in the repo, it is just not checked out
* it shouldn't matter whether a perennial branch is currently checked out in the workspace

I suggest the setup wizard just checks that a perennial branch exists in the repo, but not in the workspace.

<img width="732" alt="__n_documentation" src="https://cloud.githubusercontent.com/assets/268934/10822480/d8b454d6-7e2d-11e5-91c2-4b4c7607ad05.png">

**Comment by aricahunter** [comment]
@kevgo 
Someone must've already fixed this. I've checked and it definitely doesn't require the branch to have been checked out. It checks if the branch you provide is in the list of remote branches.

**Comment by charlierudolph** [comment]
Confirmed @aricahunter's findings. Closing.
