### ISSUE TITLE
git-ship: make GitHub compatible

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#705]
As a developer using GitHub and related tools
I want my shipped branches to show up as "merged" on GitHub
So that I and my tools know which branches have been shipped and which have been deleted.

Rules:
- to ship: 
  
  ```
  git reset <main-branch-name>
  git add -A
  git commit
  git push --force
  git checkout <main-branch-name>
  git merge --no-ff <main-branch-name>
  ```
- providing the option `--squash` to `git-ship` does the old behavior of doing squash-merges

**Comment by charlierudolph** [comment]
Just did a test, and in order for github to mark a pull request as merged, we will need to force push the squashed branch first. Resetting locally and then merging does not mark the branch as merged.

Also need a `git add -A` between the reset and the commit

**Comment by kevgo** [comment]
Alright, I have updated the ticket description.

**Comment by charlierudolph** [comment]
Closing in favor of the resolution of #750
