### ISSUE TITLE
git-new-pull-request: squash the branch before sending off the pull request

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#706]
As a developer working on a team that merges feature branches using the GitHub UI
I want to squash my feature branches into a single commit before sending off pull requests
So that Git Town conforms to and supports my team workflow.

**Rules:**
- to squash a feature branch:
  - `git reset <main-branch-name>`
  - `git commit`
  - `git push --force`

**Questions:**
- do we let the user enter the same commit message over and over for each squash?
  - if yes, can we suggest the old commit message as the new one?
  - if no, when does the user have a chance to fine-tune the final commit message?

**Comment by charlierudolph** [comment]
Closing in favor of the resolution of #750
