### ISSUE TITLE
git-sync: GitHub-compatible behavior

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#707]
As a user working on a branch that was squashed on another machine
I want that any merge conflicts are resolved by `git sync`
So that using the new GitHub-compatible workflow isn't more cumbersome or weird than the existing behavior.

**Rules:**
- hopefully this behavior works:
  
  ``` bash
  git reset <parent branch name>
  git stash -u         # at this point the branch has no changes and is similar to its parent --> conflict-free pull
  git pull 
  git stash pop      # Replay any changes from the feature branch on top of the existing changes. 
  git commit
  ```

**Comment by JaKXz** [comment]
@kevgo not sure if this is related, but I'm seeing issues whenever there are merge conflicts when running  `git sync`, after fixing the conflicts `git sync --continue` throws an error saying something about `--continue` not being an option available to `git sync`? Not really sure what's going on there so I usually just ignore it [and it's somewhat of an edge case].

**Comment by kevgo** [comment]
I think that's another issue, since this ticket is about a feature that doesn't even exist yet. Can you please file a separate bug report for this?

**Comment by charlierudolph** [comment]
Closing as have closed a few other issues related to this milestone since we now have ship via the github API
