### ISSUE TITLE
`git new-pull-request` is broken after solving conflicts during sync

### ISSUE THREAD

**Issue by daviscabral** [Originate/git-town#714]
When trying to create a new pull request from a branch that is not synced - and has conflicts, I get the following output:

    $ git new-pull-request
    <...>
    [...] git merge --no-edit develop
    <...>
    Automatic merge failed; fix conflicts and then commit the result.

    To abort, run "git new-pull-request --abort".
    To continue after you have resolved the conflicts, run "git new-pull-request --continue".

So, after solving the conflicts, when I try to resume the process - no PR is created and it is finished like this:

    $ git new-pull-request --continue
    <...>
    [...] git commit --no-edit
    [...] Merge branch 'develop' into <...>

    [...] git push
    <...>
    /usr/local/Cellar/git-town/0.9.0/libexec/helpers/script_helpers.sh: line 148: create_pull_request: command not found

    To abort, run "git new-pull-request --abort".
    To continue after you have resolved the conflicts, run "git new-pull-request --continue".

**Comment by charlierudolph** [comment]
Please upgrade to 0.10. This was recently fixed.

**Comment by daviscabral** [comment]
Awesome, thank you.
