### ISSUE TITLE
Git hack does not hack off a parent feature branch

### ISSUE THREAD

**Issue by angrygoats** [Originate/git-town#716]
@kevgo 

After doing a bunch of tests over on nucleus, if I use `git hack tb-my-new-feature tb-my-parent-feature` it doesn't seem to work. The way I confirmed it is by switching to the new feature, and diffing it against the parent.

Its possible I'm doing something wrong here. Can anyone else confirm this?

**Comment by charlierudolph** [comment]
Everything appears to be correct. What version of git town are you using? Nested feature branches were added in 0.7

**Comment by charlierudolph** [comment]
This functionality is working for me and I'm using 0.10.

**Comment by angrygoats** [comment]
@charlierudolph Indeed, it appears what was happening was my standard brew upgrade wasn't upgrading git-town. It was refusing quietly. Forcing an upgrade fixed it, though it might be worth looking into why brew keeps demanding my github credentials to upgrade git-town.

**Comment by charlierudolph** [comment]
Hmm. We were originally on our own homebrew tap, Originate/gittown, but moved to the official tap in September of last year. Is git-town the only tap where brew is demanding your credentials?

**Comment by allewun** [comment]
I also encountered homebrew asking for credentials. Based on [this](https://github.com/Homebrew/homebrew/issues/18432), it's because the tap repo doesn't exist (I had `brew tap originate/gittown` in one of my setup scripts).
