### ISSUE TITLE
perennial branch: parent branch

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#727]
When syncing a perennial branch for the first time, when being prompted for that branches parent branch, if would be nice if there was an easy way to basically say it has no parent and is thus a perennial branch. 

Maybe entering itself as the parent branch? Or maybe adding another question where the user is asked if the branch is perennial?

**Comment by kevgo** [comment]
Yes, we could allow the user to enter "perennial" or the branch name itself.

**Comment by charlierudolph** [comment]
This was closed by mistake.

**Comment by charlierudolph** [comment]
@kevgo thoughts on making one of the numbered options `<none> (perennial branch)`?

**Comment by kevgo** [comment]
I like that
