### ISSUE TITLE
git-new-pull-request: custom PR commands

### ISSUE THREAD

**Issue by colinsf** [Originate/git-town#737]
allow a `.gitconfig` override for custom PR commands outside of GitHub/Bitbucket

**Comment by kevgo** [comment]
Can you please share details which service you use? Maybe we can add a driver for it.

**Comment by charlierudolph** [comment]
@colinsf bump. Any response to @kevgo's question?

**Comment by charlierudolph** [comment]
Closing due to lack of response. Please reopen if necessary

**Comment by colinsf** [comment]
heyyy sorry i ignored this forever

self-hosted gitlab was my target use case

**Comment by charlierudolph** [comment]
gitlab support was added in 3.1.0. Please try that out as it may cover your use case. [docs](https://github.com/Originate/git-town/blob/8b47093d0db3ea530b1fa750dfb93dcf165d3e52/documentation/commands/git-town-new-pull-request.md)

**Comment by colinsf** [comment]
:beers:
