### ISSUE TITLE
Using ssh with multiple keys to clone repos disable use of 'new-pull-request' and 'repo' commands.

### ISSUE THREAD

**Issue by avaz** [Originate/git-town#739]
Hi,

I have different accounts in Github and Bitbucket and to access them I use ssh with multiple keys. So in my ssh config file I have something like:

```
Host bitbucket-as-account2
  HostName bitbucket.org
  User git
  IdentityFile /Users/anderson/.ssh/id_rsa.pub
  IdentitiesOnly yes

Host github-as-account1
  HostName github.com
  User git
  IdentityFile /Users/anderson/.ssh/dev_andersonvaz_rsa.pub
  IdentitiesOnly yes
```

And to clone repos of these servers I do something like:
`git clone git@github-as-account1:user/repo.git`

Everything works except for the `new-pull-request` and `repo` commands that raise the error bellow:

```
Error
  Unsupported hosting service.
  This command requires hosting on GitHub or Bitbucket.
```

It can't identify which server is being used.
I don't think that it's a bug so I will let this here as a suggestion.
If was possible to specify which hosting service the pull request should be created or automatically resolves from ssh `config` file which service the repo is using would be nice.

**Comment by kevgo** [comment]
Thanks for letting us know! This is probably just because our current regex isn't flexible enough to ignore SSH identities in the Git remote URLs. Will fix in the next version!
