### ISSUE TITLE
git-town-branch config for deleted branches

### ISSUE THREAD

**Issue by kelbyers** [Originate/git-town#741]
I happened to notice that in my .git/config, information for git-town remains behind after branches are deleted. All of the branches that I have ever worked on with git-town are still in the config, long after they have been deleted on both the local repo and on my remotes.

`git town config --reset` does not remove them, and after re-running `git town config --setup`, they are all back in the output of `git town config`, and looking at the contents of .git/config, they are never even touched doing the `--reset`.

Is there some way to remove all these old branches without manually editing .git/config?

**Comment by kevgo** [comment]
Thanks for reporting this! If you use `git kill` or `git ship`, this metadata should be cleaned up. Are you deleting your branches in another way?

**Comment by kelbyers** [comment]
Yeah, I am not working directly on github.com, but on Enterprise github, hosted for my employer, so `git ship` doesn't work. I haven't tried `git kill`.

What I normally do is to just do a PR on our github server, and delete the branch as part of the merge, then locally I prune and delete my local branch git `git branch -d`.

**Comment by kelbyers** [comment]
Looking at the docs, looks like `git kill` should work for me after doing the merge. I think I was aware of the command, and didn't consider using it for anything other than removing a branch I decided I didn't need, but wasn't going to merge.

Thanks!

**Comment by charlierudolph** [comment]
`git prune-branches` will delete any branches that have that remote deleted

**Comment by kelbyers** [comment]
@charlierudolph: does that also take care of doing the `git remote prune`, to clean up the remote-tracking info?

**Comment by charlierudolph** [comment]
It doesn't run `git remote prune`. It just fetches and then deletes any local branch whose remote has been deleted

**Comment by kelbyers** [comment]
Does it also clean up the git-town-branch items in .git/config? That is what my main concern is about: cleaning up the config data.

**Comment by kevgo** [comment]
@kelbyers running `git sync`, `git kill`, `git hack`, or `git prune-branches` runs `git fetch --prune`, which should do the same things as `git remote prune`.

We should add logic that resets all Git Town config data from the Git repo when running `git town --reset`. 

Btw, why can't you use `git ship` in your particular setup?

**Comment by kelbyers** [comment]
Huh, for some reason, I thought that `git ship` also connected to github.com and opened a pull request. And I might have also thought it automatically did something to deploy to servers. Looks like I could use it, except that our team workflow uses PRs to do peer reviews.

**Comment by charlierudolph** [comment]
We use `git ship` with PRs. We create PRs and get reviews and then merge the PR with `git ship`. Prior to github implementing the ability to squash merge PRs, that was a big difference maker. 

`git ship` is still nice as it does all the branch cleanup for you.

Otherwise you still need to delete the remote and local branches. Github has a button to delete the remote branch but you need to remember to press it after you merge. If you have deleted the remote branches of your merged PRs, then you can use `git prune-branches` to delete the corresponding local branches.

**Comment by kevgo** [comment]
@kelbyers only `git new-pull-request` creates a new PR on Github. `git hack`, `git sync`, `git ship`, and `git kill` are completely agnostic of GitHub, and can be used with any Git hosting platform. The only thing to look out for is that `git ship` does [squash merges](https://github.com/blog/2141-squash-your-commits). That's the right way to do it in our opinion, but can cause issue if not the whole team ships branches this way. Fortunately, GitHub has a configuration switch to enforce squash merges for a repo.

**Comment by charlierudolph** [comment]
Closing in favor of #777. Please reopen if anything else needs to be discussed
