### ISSUE TITLE
git town-repo: support GitLab

### ISSUE THREAD

**Issue by JaKXz** [Originate/git-town#742]

**Comment by charlierudolph** [comment]
@JaKXz would you be willing to try to implement this? I don't use Gitlab and I would rather had someone who does implement it. 

I believe implementing this would only require adding a [driver](https://github.com/Originate/git-town/tree/master/src/drivers/code_hosting) and some [feature tests](https://github.com/Originate/git-town/tree/master/features/git-town-repo). If we are going to add support for GitLab we should also implement git-town-new-pull-request. 

If you're willing to implement this please read through our contributing docs on how to get setup. I'm also here to help if you need any assistance

**Comment by charlierudolph** [comment]
Fixed in #790
