### ISSUE TITLE
Add git pull-request support for Github Enterprise

### ISSUE THREAD

**Issue by ProLoser** [Originate/git-town#749]
Support currently exists in https://github.com/github/hub

**Comment by charlierudolph** [comment]
I have never used github enterprise so can you please give more detail about what exactly you are looking for?

All git-town needs to know is
* What does the remote url look like? (git remote -v)
* What should the pull request url be and how is it related to the remote url?

If you would like to implement this, I am happy to point you in the relevant directions.

**Comment by charlierudolph** [comment]
related to #654

**Comment by kevgo** [comment]
This should work now, closing. Please repopen if this is still an issue.
