### ISSUE TITLE
Use Github API to ship branches on Github

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#750]
> As a developer working on a repository on Github
> I want to ship the branch using the Github API instead of using Git commands on my machine
> So that Github shows the correct merge status and I can take advantage of branch protection, CI, and review approvals.

This PR would resolve #539, #673, #705, #51, #201, #445 

Notes
- create a [personal access token](https://github.com/settings/tokens)
- store the token in the Git Town configuration for the project
- get the PR number by [listing all pull requests](https://developer.github.com/v3/pulls/#list-pull-requests) with the `head` parameter set to filter by branch name
- [merge the PR](https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button)

**Comment by charlierudolph** [comment]
* Requires the user giving use a personal access token from github
  * see the last line of this [doc](https://developer.github.com/v3/auth/#working-with-two-factor-authentication)
* Get PR number via branch name
  * [doc](https://developer.github.com/v3/pulls/#list-pull-requests)
  * use the `head` filter
* Merge PR
  * [doc](https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button)
  * Use the `squash` and `commit_message` parameters

**Comment by charlierudolph** [comment]
Resolved by #937 and #1006. Released in 4.2.0
