### ISSUE TITLE
git sync: resolving merge conflict that results in no changes

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#753]
Ran into this a couple times. Syncing a branch and running into a merge conflict with the main branch. I resolve the conflict and add the file. Resolving the conflict results in no changes. The following is what git status looks like:

```
$ git status   
On branch cr-rewrite
Your branch is up-to-date with 'origin/cr-rewrite'.
All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)
```

When running `git sync --continue` it prints a single empty line and exits. The branch does not get pushed and trying to continue again says `The last command finished successfully and cannot be continued`

Running `git sync` a second time on the same branch, if I add the file and run `git commit` before running `git sync --continue` it works as expected and pushes the branch up

**Comment by kevgo** [comment]
Yes, merge conflicts that don't result in changes require a manual commit before running `git sync --continue`. The command should recognize and handle this situation on its own.
