### ISSUE TITLE
Modify git-town to run in bash.exe provided by Git for Windows

### ISSUE THREAD

**Issue by alexedelsburg** [Originate/git-town#754]
I love the simplicity provided by git-town on my Mac and was curious to see what it would take to get it working on Windows too

**Comment by kevgo** [comment]
+1 Windows compatibility would be great, a PR is welcome!

**Comment by kevgo** [comment]
Good news, version 4.0 should run natively on Windows! This is untested, so please report any issues encountered as new tickets!
