### ISSUE TITLE
Deploy via CI

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#761]
Ideally the deployment happens via the CI server, so that it is easier to do

**Comment by charlierudolph** [comment]
Steps from homebrew contibuting doc

---

### Submit a `1.2.3` version upgrade for the `foo` formula

* check if the same upgrade has been already submitted by [searching the open pull requests for `foo`](https://github.com/Homebrew/homebrew-core/pulls?utf8=✓&q=is%3Apr+is%3Aopen+foo).
* `brew edit foo`
* edit [`url`](http://www.rubydoc.info/github/Homebrew/brew/master/Formula#url-class_method) and [`sha256`](http://www.rubydoc.info/github/Homebrew/brew/master/Formula#sha256%3D-class_method)/[`tag`](http://www.rubydoc.info/github/Homebrew/brew/master/Formula#url-class_method), leave the [`bottle`](http://www.rubydoc.info/github/Homebrew/brew/master/Formula#bottle-class_method) as-is
* `brew install --build-from-source foo`
* run `brew audit --strict foo` and fix any issues
* `git commit` with commit subject `foo 1.2.3`
* [open a pull request](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) and fix any failing tests

---

Preconditions:
- fork of `Homebrew/homebrew-core` CI can read/write

Steps:
- clone the homebrew fork
- sync with upstream
- hack a new branch
- Edit `Formula/git-town.rb`
- Update the url
- Download the file at the url, get the sha256 (see our contributing doc)
- Update the sha256
- Run the other steps brew suggests 
- Create a PR (using hub?) 
  - need to tag at least one maintainer of git-town so we get notifications if the PR reviewer requests any changes (I'm assuming the PR is made with an Originate bot github account)

**Comment by charlierudolph** [comment]
@kevgo do we have an Originate github account that we could use for this?

**Comment by kevgo** [comment]
Can we use our normal Github account for this ("github.com/originate")? It uses the email `hello@originate.com`.

**Comment by charlierudolph** [comment]
Yeah that should be fine. Hmm, will be interesting to see if brew will install on a linux machine (in order to run the brew test commands) or if we need to switch to a OSX machine on circle in order to deploy. I'll look into this later this week.

**Comment by kevgo** [comment]
Good point. The normal Mac version won't work here, but there is http://linuxbrew.sh, which is Homebrew for Linux. Hopefully it is compatible enough. 

If we get this running, we could possibly also use it to avoid the issues we had with the built-in package managers on Linux.

**Comment by charlierudolph** [comment]
Just learned this may be easier thanks to the brew developer command `brew bump-formula-pr`

**Comment by charlierudolph** [comment]
Publishing the executables is done via CI and I haven't had to make a PR to homebrew recently. It appears @ilovezfs has a way to know what formulas need to be updated and then runs their handy tool `brew bump-forumla-pr`
