### ISSUE TITLE
error when syncing a new branch hierarchy

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#784]
steps to reproduce:
- `origin` contains branches `test-1` and `test-2`
- `test-1` is set as a child of `master`
- check out `test-2`
- run `git sync`
- when it asks for the parent of `test-2`, enter `test-1`

expected behavior:
- the sync finishes successfully

actual behavior:
- the command crashes with the error message: `Nested branch loop detected: 'test-2' is an ancestor of 'test-1'

**Comment by charlierudolph** [comment]
Yeah I've ran into this a couple times as well. Been meaning to create the bug report for it.

**Comment by charlierudolph** [comment]
Fixed in a5732e9
