### ISSUE TITLE
Prevent Ship When Requirements Aren't Passing

### ISSUE THREAD

**Issue by blainemuri** [Originate/git-town#812]
Right now when I ship a branch, it will merge regardless of the branch protection.

When branch protection is enabled on GitHub, and my PR doesn't fulfill the requirements of the branch protection (i.e. passing CI), I want a fail message to appear. Protection options should be similar to the options listed below.

![screen shot 2017-03-16 at 10 31 44 am](https://cloud.githubusercontent.com/assets/5514877/24009990/c7af8b9a-0a33-11e7-9ce5-c31913768c87.png)

**Comment by charlierudolph** [comment]
Now that we `git ship` can merge via the github api (released in 4.2.0), the branch protection provided by github should now work with `git ship`
