### ISSUE TITLE
git town config

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#823]
Currently we have a lot of configuration logic at the top level. 
```
usage: git town
   or: git town alias (true | false)
   or: git town config [--reset | --setup]
   or: git town hack-push-flag [(true | false)]
   or: git town help
   or: git town install-fish-autocompletion
   or: git town main-branch [<branch_name>]
   or: git town perennial-branches [(--add | --remove) <branch_name>]
   or: git town pull-branch-strategy [(rebase | merge)]
   or: git town version
```

I don't really like these being at the top level if we are going now that everything is going to be a  subcommand of `git-town` so those would appear in the same list as `hack`, `sync`. To keep those commands at the forefront, I'd prefer we do the following
* move help and version to options, (--help and --version) 
* move `alias`, `hack-push-flag`, `install-fish-autocompletion`, `main-branch`, `perennial-branches` and `pull-branch-strategy` as subcommands of config

**Comment by kevgo** [comment]
Hmm, I was thinking the opposite: now that we have a better structure for commands, make all these things real commands. Alternatively we can rename the `town` command to `config`.

**Comment by charlierudolph** [comment]
I'll leave these as is with the go rewrite. We can revisit this later if need be.
