### ISSUE TITLE
Have a configuration option to ship to upstream?

### ISSUE THREAD

**Issue by alexw10** [Originate/git-town#830]
Currently the git town-ship will not push directly to upstream.
This is a bit annoying and I think it would be awesome if there was an option where it would directly ship to origin and upstream.

**Comment by kevgo** [comment]
Can you please describe the use case you have in mind for this? 

When you say `upstream`, I assume you are working on a forked repo, and want to ship a pull request into the repository you forked from. Typically, that's not allowed or intended. Only developers of the upstream repo should be able to pull your changes into their repo.

**Comment by dalelotts** [comment]
Hi @kevgo, I work with @alexw10.  

In this case, our team uses the forking model for our day-to-day development, so we want to push to upstream when we ship.

As it is right now, we have to do `git town-ship [branch-name]` then immediately follow that with `git push upstream master`  Unfortunately, at least once a week one of us forgets to push upstream after shipping and things are a bit out-of-whack.

Having some way to include a push to upstream as part of `town-ship` would save us from accidentally missing that step. 

I have no idea how common this practice is for other teams.

**Comment by kevgo** [comment]
Thanks for the background, @dalelotts! What is the motivation behind your setup? I want to understand the benefits of it better before supporting it officially in Git Town.

Typically, I am aware of two typical setups:

__A) trusted collaborators__
  - this is typical in normal developer teams
  - the collaborators have write access to the repo
  - they create feature branches inside the repo and make a pull request from their feature branch against master
  - they use the normal `git town-ship` command to merge their feature branches into the master branch
  - this is also called [Github Flow](https://help.github.com/articles/github-flow)

__B) untrusted collaborators__
  - this is typical for external developers, for example around open source projects, where you don't want to give them the ability do modify your code base without your approval
  - the collaborators don't have write access to the repo
  - they clone the repo and make a pull request into the upstream repo
  - the owner of the upstream repo accepts the changes and merges them into the upstream repo

In your situation, the developers seem to have access to push to the master branch of the upstream repo. It's not clear to me why you make them fork the repo and go through the overhead of keeping their fork in sync with the upstream repo. 

If you want a short-term solution, you could create a Bash file called `git-ship`, containing:

```bash
#!/usr/bin/env bash
set -e

git town-ship "$@"
git push upstream master
```

Just call is `git ship`, and it will do the ship and then the push to upstream.

**Comment by alexw10** [comment]
@kevgo so the two setups you describe is exactly correct. In our case the our main team working on what we are is both of the setups you described this we always want to push to upstream after we ship when we are working on stuff.

We have the fork setup still because we are allowing outside contributions still as well. I think the different is that we are also on forks as well the main team that is.

I think what you are saying is why have us do forks at all correct? Our team could just work directly off master with branches and outside contributions could use the fork model is this correct?

**Comment by dalemanthei** [comment]
What do you think if we were to use a shared fork and designate it the perennial branch for our team? Would that change how git town works?

**Comment by dalelotts** [comment]
@dalemanthei I don't think that works any better since there is still an upstream repository.

**Comment by alexw10** [comment]
@kevgo I think you can close this as we have decided, that our team can still use the fork method if they want to but can also just work directly off master like you have suggested.

Thanks for your insight @kevgo ! :)

**Comment by kevgo** [comment]
Great, I'm happy we could resolve this! To summarize, I am proposing:
* No more forked repos for the internal team. Your internal team works completely inside the upstream repo. They make changes in feature branches, then merge those feature branches into the master branch. 
* no change to how your external contributors work.

I'm closing this issue, as requested.
