### ISSUE TITLE
New Pull Request Prompted for Perennial Branch's Parent

### ISSUE THREAD

**Issue by dhakiki** [Originate/git-town#832]
Master is a known perennial branch. However when I create a new pull request, I see the following message.

![screen shot 2017-04-03 at 6 57 53 pm](https://cloud.githubusercontent.com/assets/2328865/24638703/8eb616c2-189f-11e7-9623-09429bef416c.png)

If I enter nothing, the solution is incorrect, if i enter master an error will appear

@charlierudolph

**Comment by kevgo** [comment]
Thanks for reporting this issue. Hopefully our [rewrite in Golang](https://github.com/Originate/git-town/commits/go) will fix this issue. We will look at this bug again after that is done.

**Comment by charlierudolph** [comment]
Unable to reproduce with the current version
