### ISSUE TITLE
hack-push-flag confusion

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#859]
Looking at the code, the hack-push-flag applies to append / hack / prepend. 
Should we rename this flag so its more clear that it applies to all three?
The documentation only mentions hack and thus at the very least it needs to be updated that it applies to all three.

Related Note: We currently only have tests that it applies to hack and thus we need to add tests that it applies to append / prepend.

**Comment by kevgo** [comment]
Maybe call it `branch-push-flag`, or to be more specific `new-branch-push-flag`?

**Comment by charlierudolph** [comment]
I like `new-branch-push-flag`
