### ISSUE TITLE
Rename "When I run" to "When running"

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#871]
it reads better

**Comment by morrme** [comment]
I'd like to help.

**Comment by kevgo** [comment]
Hey @morrme, thanks for offering help, this is highly appreciated! This particular issue is already implemented in #873, which is currently under review. Feel free to pick another issue, or let us know if you want us to propose another Cucumber related for you!

**Comment by kevgo** [comment]
We decided to rename this to "When xxx is run"
