### ISSUE TITLE
Improve function names

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#882]
- rename `UpdateMainBranch` to `ConfigureMainBranch`
- rename `UpdatePerennialBranches` to `ConfigurePerennialBranches`

**Comment by morrme** [comment]
Is this one available?

**Comment by kevgo** [comment]
Yes, please take a stab at it, @morrme! Please make sure to cut your feature branch off the `go` branch, not master, since the Go rewrite hasn't shipped to production yet. Looking forward to your pull request!  😃

**Comment by morrme** [comment]
@kevgo I could only find 3 references to each function. Does that sound right?

**Comment by kevgo** [comment]
Yes, that sounds right. If the code base still compiles, this rename has been done correctly.
