### ISSUE TITLE
switch to TravisCI

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#890]
- Travis is faster because it is Docker based. Circle has a 30 second startup time to get the VM ready
- Travis is public, so it also tests PRs from external contributors
- Travis has built-in support for attaching files to Github releases

**Comment by morrme** [comment]
I'm guessing this has to be done by someone internally (since it requires admin permissions)?

**Comment by kevgo** [comment]
@morrme yes, this requires admin access. What do you think about these tickets:

* #859: rename `hack-push-flag` to `new-branch-push-flag`
* #887: a simple bug fix in our new Go implementation
* #853: improve output when running in a non-Git directory
