### ISSUE TITLE
Merge From Branch To Master Deleted File

### ISSUE THREAD

**Issue by blainemuri** [Originate/git-town#892]
After committing work on HEAD@{67}, working for a file called `map/index.jsx` was successfully saved.

Below is the squashed commit messages:
![screen shot 2017-05-08 at 9 21 11 am](https://cloud.githubusercontent.com/assets/5514877/25813779/b6ddc1d6-33cf-11e7-8172-4adb83cfcd6a.png)

At HEAD@{68}: checkout, the branch maintains those changes. Then at HEAD@{69}, when using git town-ship to merge into master, the final push no longer contains the changes for `map/index.jsx`

**Comment by blainemuri** [comment]
After looking at this further, I realized that it also deleted my very last commit. There should have been one more there

**Comment by blainemuri** [comment]
Each other branch in my pipeline got the changes of HEAD@{67} merged into them as well. i.e. this code somehow got merged into every branch, not just my current (the command run was `git sync`)

**Comment by charlierudolph** [comment]
Sorry to hear about the lost file. Is there anyway you could create a reproducible example of this bug? At the moment I don't really know what to investigate. We've heard of git-town [deleting files](https://github.com/Originate/git-town/issues/744) once before, but believe we fixed that.

Does the missing commit include the deleted file? In which case its might be better to focus on that.

**Comment by kevgo** [comment]
Can you please provide more details? Into which branches did you commit what? Which Git Town commands did you run? Without those, it is hard to understand exactly what went wrong, and how.

Did you experience merge conflicts while shipping, and are you sure you resolved them correctly?

**Comment by charlierudolph** [comment]
Closing due to lack of response. Please reopen if there is more to discuss
