### ISSUE TITLE
Git town command not found

### ISSUE THREAD

**Issue by andrecavallari** [Originate/git-town#909]
Since I am using Linux, I always install using the manual installation: http://www.git-town.com/install.html
But now I installed as always I did, and always worked fine, but now when I type "git town" I have this error:
git: 'town' is not a git command. See 'git --help'

When I saw the src directory, there is no executables there anymore... What do I need to do??

**Comment by charlierudolph** [comment]
The latest release was a rewrite in go and we still need to update the install instructions. You can grab the appropriate binary from https://github.com/Originate/git-town/releases/tag/v4.0.0 rename it to git-town and put it somewhere in your PATH.

**Comment by charlierudolph** [comment]
Created #910 to track updating the install instructions
