### ISSUE TITLE
Broken links on http://www.git-town.com/

### ISSUE THREAD

**Issue by mictab** [Originate/git-town#920]
Hi!

The links in the section "Powerful Commands" at http://www.git-town.com/ are broken right now. It looks like the latest version of the website hasn't been deployed. https://github.com/Originate/git-town/blob/master/website/index.jade

**Comment by allannienhuis** [comment]
Probably related to this, the installation instructions are not accurate as of the latest commit.  Right now new users can't install based on your published install documents, as the README in github also points to the website for install instructions.  Perhaps the README might also link to the appropriate file in github?

**Comment by charlierudolph** [comment]
New version of the website deployed and the links work for me. @allannienhuis the manual install instructions should be up to date now. I'll create a new ticket for updating the linux distributions.

**Comment by allannienhuis** [comment]
awesome, thanks!!  Yes, the link in the readme worked - it was just pointing to the (no longer) out of date website.  I was suggesting considering linking to a document completely hosted within github (ie another markdown document) to avoid that situation.  Just a suggestion; not an actual request :) Thanks for the useful tool! :)
