### ISSUE TITLE
update linux install instructions

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#924]
With 4.0.0, I would guess the `ARCH LINUX` and `DEBIAN/UBUNTU BASED DISTROS` need some updates. @allonsy could you help in this matter? Note we now have all the needed binaries on the releases page but can also build the binary if needed (which homebrew is doing)

**Comment by allonsy** [comment]
I've updated the arch linux package on the AUR to use the new binary (I just pull from the releases page) so that arch linux installation instructions should be the same.

The ubuntu instructions should also be the same except I haven't yet updated the ubuntu build scripts so the `deb` package currently builds an old version. I'll get working on making a new `.deb` package for debian/ubuntu distros

**Comment by charlierudolph** [comment]
Awesome. Thank you very much @allonsy

**Comment by allonsy** [comment]
I'll have the deb file finished up by this weekend and then I'll pass along the file to be added to the releases page.

**Comment by kevgo** [comment]
Excellent, @allonsy! With 1200 Github stars, we are now seeing a ton of interest from Linux users, so having an easy way to install Git Town on Linux will help both causes tremendously and makes the world a better place!

**Comment by allonsy** [comment]
Sorry for the delay!
Here is the deb file in zip format. Can someone download this file, unzip it and attach it to the releases page (I have already verified that it works).
[git-town_4.0.1.deb.zip](https://github.com/Originate/git-town/files/1037030/git-town_4.0.1.deb.zip)

I also have updated packaging instructions for us which I will submit in a PR momentarily. For end users, the install instructions are all the same as what we have in the repo, the new instructions are just for our 
 own use when we want to generate new deb files.

**Comment by kevgo** [comment]
The `deb` file is attached to the latest build. Is there a way to do this automatically on the CI server? Currently, each time there is a Git tag, we cross-compile the different binaries on Travis, put all files into the `dist` directory on Travis, and Travis then attaches all files in that directory to the Github release automatically. Is there a way to build the `deb` file the same way and throw it into the `dist` directory as well?

**Comment by allonsy** [comment]
Once #950 is merged, we can close this issue

**Comment by allonsy** [comment]
@kevgo @charlierudolph 
Now that debian build process is automated from travis, can someone close this issue as resolved (the instruction in `packaging.md` are all up to date)?

**Comment by charlierudolph** [comment]
Closing. Thanks @allonsy!
