### ISSUE TITLE
Error when running `sync` on Windows 

### ISSUE THREAD

**Issue by atanasbozhkov** [Originate/git-town#925]
I am running git-town installed manually in a directory on %PATH% on Windows 7.

When I first ran `git-town sync` I got the following error on the Stash Pop step after pulling changes down.

`CONFLICT (content): Merge conflict in src/test.js
2017/05/22 11:29:28 open /tmp/sync_C:_Projects_myProject: The system cannot find the path specified.`

I can resolve the conflict manually - but I'm guessing something when wrong there.

If I've omitted/forgotten any important information let me know so I can update the issue.

A

**Comment by charlierudolph** [comment]
`git-town` saves some state in temporary files if there are conflicts or if the command is undoable. Is `/tmp/sync_C:_Projects_myProject` a valid path on a windows machine?

**Comment by atanasbozhkov** [comment]
It shouldn't be a valid path on Windows - AFAIK Windows does not allow for ":" in folder names.

**Comment by charlierudolph** [comment]
Okay. Currently the temp file includes the full path to the repository with the "/" converted to "_". We can add a conversion to remove the ":".

**Comment by kevgo** [comment]
While we are at it, let's convert all non-alphanum characters to underscores to solve this once and for all, for all platforms.

**Comment by charlierudolph** [comment]
4.1.0 released with a fix
