### ISSUE TITLE
Fork & remote update integration

### ISSUE THREAD

**Issue by ad-m** [Originate/git-town#928]
Hi,

Frequently participating in open-source projects. When this is done, the project repositories clone. When I find a bug I need to create a fork, update the remote, then create a new branch, update the branch's default locations, then make changes to the code, commit changes, push the new branch, make pull requests to a capable repo (sometimes I fork the fork and I would like add pull request to to the fork).

Can this workflow be more strongly supported by this project?

Greetings,

**Comment by charlierudolph** [comment]
Hi @ad-m. I use git-town pretty frequently with open source projects. The main pattern git-town follows what [GitHub](https://help.github.com/articles/fork-a-repo/) suggests where the source you are forking from should be added as a remote named upstream.

There is a mention of `upstream` at the bottom of the git sync [docs](https://github.com/Originate/git-town/blob/128ee85b04bcb9c2c936a6b0ec8040f46a59443e/documentation/commands/sync.md) and this [feature](https://github.com/Originate/git-town/blob/128ee85b04bcb9c2c936a6b0ec8040f46a59443e/features/git-town-sync/current_branch/main_branch/no_conflict/with_upstream.feature) which showcases it.

Can you be more specific about what integrations would help in your workflow? (for example what additional command you want run, etc)

**Comment by waldyrious** [comment]
@ad-m, in case you don't know, the [hub](https://hub.github.com/) tool ([usage summary](https://github.com/tldr-pages/tldr/blob/master/pages/common/hub.md)) helps with some of these tasks. One thing it doesn't do (see https://github.com/github/hub/issues/1368), that maybe git-town could help with, is syncing a fork. Given the title of this issue, I suppose @ad-m would like this too.

**Comment by charlierudolph** [comment]
Git Town does work well with syncing forks and I use it constantly for that. The `new-pull-request` command also works well when you need to make a PR to the fork on github.

**Comment by charlierudolph** [comment]
Closing as the question appears to have been answered. Please reopen if there is more to discuss
