### ISSUE TITLE
Make hack-push-flag false by default

### ISSUE THREAD

**Issue by waldyrious** [Originate/git-town#929]
This is slightly related to #659: git town shouldn't do stuff with permanent effects (such as publishing a branch) that the user has not previously consented to. This is the case the first time one runs `git town hack <branch>`, when it is arguable that they might not know git town is going to push the branch upstream.

Perhaps the first run of the git town hack command could ask for the desired value of this configuration, but that's an extra feature -- in any case, the default should be false.

By the way, doing this could mitigate #689 (for the first invocation of `git town hack`, at least).

**Comment by kevgo** [comment]
I agree with this. Pushing empty branches causes more stress on the CI server, which occupies precious server time when using the free plan of TravisCI for open-source projects. Let's make this flag false by default.

**Comment by charlierudolph** [comment]
I'm good with this. @kevgo would this be a breaking change?

**Comment by kevgo** [comment]
It's a **change** if the user didn't set the config flag. It shouldn't **break** anybody, though. So, a change, but not a breaking change. How do you feel about bumping the minor version number here?

**Comment by allewun** [comment]
👍 I support this change as well. It falls in line with how I've been using Git Town since day 1.

**Comment by charlierudolph** [comment]
Sounds good. Minor change it will be. I should be able to get to this today.

**Comment by charlierudolph** [comment]
4.1.0 released with this change
