### ISSUE TITLE
Gogs support

### ISSUE THREAD

**Issue by bang88** [Originate/git-town#933]
Any chance to support https://github.com/gogits/gogs PR.

thanks

**Comment by kevgo** [comment]
Hey @bang88, we would absolutely accept a PR to make "git repo" and "git new-pull-request" work with Gogs! 

It should be relatively easy: just do a full text search for "bitbucket" and add Gogs to all areas you find.

**Comment by bang88** [comment]
Sounds doable. 😄

**Comment by bang88** [comment]
@kevgo but how can i make it work with our domain , are there have any docs i can read, IMO, i can't add gogs like bitbucket. if git town provide a config field that should be good to do this.

**Comment by kevgo** [comment]
Some more detailed steps, now that I'm back from a trip and at my computer:
- add a new file `gogs.go` to https://github.com/Originate/git-town/tree/master/src/drivers that matches how `gitlab.go` looks like
- add a case for gogs to https://github.com/Originate/git-town/blob/master/src/drivers/code_hosting.go#L19-L32

As you can see in the second point, we recognize a server type from the URL. So if your server URL contains `gogs`, you are good to go. If that's not the case, we might need to implement #743

**Comment by bang88** [comment]
FYI i would say if we can have custom config for other git services. just something like how to config the main branch and store it in local git repo. so we could fit many use case and no need hard coded everything in git-town.

I think this could be a more friendly for everyone who loves git-town.

As i know maybe many companies  or teams have its own git service. they may use github enterprise version or gitlab and gogs etc. we can't simply check the hostname contains these domains or check the ssh account.

if we provide a configuration then we can do more things with git-town. no limited

Thanks. 😄

**Comment by kevgo** [comment]
We can try adding a config option for the URL with placeholders. For example:
- `git-town.repo-url` = `https://github.com/Originate/git-town`
- `git-town.new-pull-request-url` = `https://github.com/Originate/git-town/compare/<PARENT-BRANCH>...<BRANCH>?expand=1`

Setting up these configuration values is a lot of manual work for the users, though. I want that they only have to do this if there is no other way. We should still support many popular hosting services out of the box. 

If you don't have the time to build the driver yourself, please just give us the URLs that:
- display the homepage of the repo on Gogs. On Github this is `https://github.com/Originate/<REPO-NAME>`
- allow the user to create a new pull request on Gogs. On Github this is `https://github.com/Originate/git-town/compare/<PARENT-BRANCH-NAME>...<BRANCH-NAME>?expand=1`

**Comment by bang88** [comment]
We use a private server and the host can access only localhost. 😢

**Comment by kevgo** [comment]
Hmm, why do you need `git repo` or `git new-pull-request` in such a scenario?

**Comment by bang88** [comment]
Just want try these featured. Haha
