### ISSUE TITLE
Deb packages missing

### ISSUE THREAD

**Issue by sivaraam** [Originate/git-town#938]
Following the [instructions](http://www.git-town.com/install.html) to install git-town on Debian, I searched for the `deb` packages in the releases. It seems that there aren't any for the releases other than version `1.0.0`. I guess the website must be updated. 

//Note// : I'm not sure where to report this and hence creating an issue in the repository.

**Comment by kevgo** [comment]
Thanks for checking in about this. @allonsy is working on releasing upgraded version for 4.0. Any updates on when those will be available?

**Comment by charlierudolph** [comment]
Closing this as duplicate of #924
