### ISSUE TITLE
Gitlab driver assumes repository is at gitlab.com rather than self-hosted

### ISSUE THREAD

**Issue by andym** [Originate/git-town#939]
My current origin is a self-hosted gitlab:

```
git config --get remote.origin.url

git@gitlab.openiimp.com:openimpdevs/platform-schema.git
```

I would expect 'git town repo' to open
https://gitlab.openiimp.com/openimpdevs/platform-schema/

but if I try the 'git town repo' command:

```
git town repo

open https://gitlab.com/openimpdevs/platform-schema
```

which is incorrect.

The gitlab driver assumes gitlab.com here at least:

https://github.com/Originate/git-town/blob/master/src/drivers/gitlab.go#L23

**Comment by kevgo** [comment]
Thanks for the bug report! You are right. Git Town should use the actual hostname of the repository URL, not `gitlab.com`.

**Comment by petr-k** [comment]
Also, git-town should not assume that the hostname actually contains the word `gitlab`. This probably implies that some additional configuration option is needed.

**Comment by kevgo** [comment]
Yes, that is definitely a planned feature. The reason why it doesn't exist so far is because nobody has requested (or implemented) it yet.  :)
