### ISSUE TITLE
Existing git town aliases no longer working; Documentation needs updating

### ISSUE THREAD

**Issue by ecbrodie** [Originate/git-town#940]
I detected this issue when I ran a `git hack` command on my machine. This had been working before the v4 release:

```
$ git hack test123
Expansion of alias 'hack' failed; 'town-hack' is not a git command
```

I preferred running this command in the old-school `git hack` way instead of `git town-hack`. Thus, I had followed the instructions on the README to set an alias:

```
git config --global alias.hack town-hack
```

It appears that this alias no longer supports aliasing the new `git town hack` binary-based command to `git hack`. Although there could be some buggy code in Git-Town preventing this alias from working, my hunch is that there is simply some outdated documentation that needs to be updated to account for Git-Town versions >= 4.

I am willing to contribute a PR to make this change. I do need to file an Issue first, though, so that I can receive guidance on what the correct new aliasing standards are. Thank you.

**Comment by kevgo** [comment]
Hey @ecbrodie! In version 4.0, the long form of the commands to run have changed from `git town-hack` to `git-town hack`. So you have to upgrade the aliases. Running `git town alias true` should do it. If you want to remove the old aliases first, run `git town alias false`, then `git town alias true` to set the new ones.

**Comment by ecbrodie** [comment]
@kevgo Thank you for the note. I have successfully changed my aliases to match the Git-Town v4 standards.

To help others like me that have updated their Git-Town versions and haven't yet realized that their aliases need to change, I have create PR #941 to update the README. Please review and merge, thank you.

**Comment by kevgo** [comment]
Thanks for helping fix the documentation, @ecbrodie! 👍
