### ISSUE TITLE
Reference-type documentation

### ISSUE THREAD

**Issue by waldyrious** [Originate/git-town#943]
Currently there doesn't seem to be a complete reference listing all the commands and the operations they perform in a single place. The website has two buttons, "See the commands" and "View all commands", and both point to https://github.com/Originate/git-town#commands, which is more of a overview/summary -- albeit with links to more detailed pages, so that's a great start.

[documentation/commands/](https://github.com/Originate/git-town/tree/master/documentation/commands) does contain a complete listing of the commands (perhaps the "View all commands" button should point to it), but one would have to open each page separately, and still those don't mention what exactly goes on behind the scenes.

The [features/](https://github.com/Originate/git-town/tree/master/features) directory does contain relevant information, like [this](https://github.com/Originate/git-town/blob/e95b86356dc7b8eeb8adb8d4dff86447eebb4ca5/features/git-town-hack/on_main_branch/with_remote_origin.feature#L18-L26), but it would be nice to be able to browse this documentation in a less contrived way.

**Comment by waldyrious** [comment]
Alternatively, the `--dry-run` option suggested in #659 could go a long way in providing this kind of information.

**Comment by kevgo** [comment]
Thanks for the pointer, @waldyrious! I agree that the website didn't list all the commands properly. I have created #944 to document the commands new in 4.0 that weren't listed there. With this in place, the documentation on Github would be the place that documents all commands. 

I will add pointers to the feature files that list the commands in a subsequent PR.

**Comment by waldyrious** [comment]
Thanks for such a quick reaction!

> I will add pointers to the feature files that list the commands in a subsequent PR.

That'd be great :)

**Comment by kevgo** [comment]
I have created #946 to create links to the Cucumber files that describe the steps from the command documentation.

**Comment by charlierudolph** [comment]
Closing in favor of #946
