### ISSUE TITLE
rename-branch should work with non-GT branches

### ISSUE THREAD

**Issue by waldyrious** [Originate/git-town#956]
```
$ git branch
  master
* mybranch

$ git town rename-branch foo

[mybranch] git fetch --prune

[mybranch] git branch foo mybranch

[mybranch] git checkout foo
Switched to branch 'foo'
2017/06/01 12:29:51 Command: git config --unset git-town-branch.mybranch.parent
Output: 
Error: exit status 5
```

Perhaps rename-branch only works on branches created by the hack command? It should work on any branch IMO, regardless of how it's created.

**Comment by kevgo** [comment]
Hi @waldyrious! Yes I agree, Git Town should allow renaming any type of branch. If the parent branch entry does not exist for it, this step should simply be skipped.

**Comment by charlierudolph** [comment]
@kevgo shouldn't we prompt for the parent branch if unknown? Thats what quite a few other commands do

**Comment by kevgo** [comment]
Should Git Town only ask for the parent branches when it needs to know that information, or always just out of principle?

**Comment by charlierudolph** [comment]
I guess git town doesn't need to know the data in this case. I'm good with only prompting when the information is required

**Comment by allewun** [comment]
This appears to work now.
