### ISSUE TITLE
Provide shorthands for common commands

### ISSUE THREAD

**Issue by arekkas** [Originate/git-town#959]
I think there should be shorthands for common commands such as `new-pull-request`, which I use a lot and is quite annoying to type. For example, `git-town pr` would probably suffice

**Comment by kevgo** [comment]
Git Town provides shorter aliases via the [alias command](https://github.com/Originate/git-town/blob/master/documentation/commands/alias.md). I'm not sure we should provide even shorter aliases. The propability of collisions with other tools like git-extras, which already has a [pr](https://github.com/tj/git-extras/blob/master/Commands.md#git-pr) command, increases. You can define your own shortcuts via normal Git aliases.

**Comment by arekkas** [comment]
I see, I didn't know about git alias, but it seems pretty straight forward.
