### ISSUE TITLE
Error when saving the command in a temporary file with Windows

### ISSUE THREAD

**Issue by hammenm** [Originate/git-town#963]
I am using git-town on Windows, and this issue is only related to this platform.

For most of the commands, I always get an error at the end of the computation, because it cannot find the temporary directory. I looked into the source code and found this in the file `step.go`:

`return fmt.Sprintf("/tmp/%s_%s", command, directory)`

I think it could be cool to change the hard-coded `/tmp/` to the location of the temporary directory for the different main OS.

**Comment by charlierudolph** [comment]
In the newly released 4.1.1, the top directory is created if it does not exist. Currently tmp is hardcoded and looking at the definition of golang's 'os.TempDir' I believe it would still return '/tmp'. To you knowledge is the temp directory elsewhere on windows?

**Comment by hammenm** [comment]
I found that the temporary directory for Windows is under `C:\Users\$USERNAME$\AppData\Local\Temp`, which is set as an environment variable `%temp%`.

I have never written anything in go, but to my knowledge, I have never seen a langage made the automatic correspondence between the path to Unix system and Windows.

**Comment by kevgo** [comment]
@hammenm which Git Town version do you use? You can find out by running `git town version`.

**Comment by hammenm** [comment]
V4.1.0

I will try the new version now.

**Comment by hammenm** [comment]
Ok, it works on 4.1.1

Thank you for your time 👍

**Comment by kevgo** [comment]
Great to hear, thanks!
