### ISSUE TITLE
invalid pre-existing configuration causes infinite loop

### ISSUE THREAD

**Issue by hammenm** [Originate/git-town#968]
Hello,

I might be in an edge case which make the ```git sync``` not work anymore.

When I am at a branch which is ```develop``` or a feature one, I have no issue with the command ```git sync```. However, when I am at the branch ```master```, and I type ```git sync```, I see the message:

```bash
[master] git fetch --prune
```

but it is blocking here, no error message. I tried to do the command without git-town and it does work.

I am willing to give logs of the situation if you show me what I should do.

Thank you for your help.

**Comment by kevgo** [comment]
Hmm, strange. Can you please post the full terminal content here? Also, the output of when you run `git branch -vv`. Thanks!

**Comment by hammenm** [comment]
```
~/Projects/my-project (master)
$ git sync

[master] git fetch --prune

(Here I did ^C to exit after 2 minutes)

~/Projects/my-project (master)
$ git branch -vv
  develop a4a4f1f [origin/develop] Minor refactoring.
* master  a4a4f1f [origin/master] Minor refactoring.
```

I did a manual merge, this is why I get this result for ```git branch -vv```. Nonetheless, the problem is still the same if develop and master have different last commit.

My main branch is develop.

Here is also what looks like my tree recently (there is not much to see unfortunately) 

![gitk](https://user-images.githubusercontent.com/9029787/27433919-eee58d66-5756-11e7-86f5-0bc4d4ceadc9.PNG)

**Comment by charlierudolph** [comment]
Can you please output the result for `git config -l`? I would guess there is some infinite loop being hit. Some configuration may have been set before we had proper checks to prevent this.

**Comment by hammenm** [comment]
Good idea! I am pretty sure I did something which was not recommended in the repo.

Here is the result of the command.

```bash
core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
rebase.autosquash=true
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.required=true
filter.lfs.process=git-lfs filter-process
credential.helper=manager
alias.append=town append
alias.hack=town hack
alias.kill=town kill
alias.new-pull-request=town new-pull-request
alias.prepend=town prepend
alias.prune-branches=town prune-branches
alias.rename-branch=town rename-branch
alias.repo=town repo
alias.ship=town ship
alias.sync=town sync
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/hammenm/zeilt_tta_standalone.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
git-town.main-branch-name=develop
git-town.perennial-branch-names=
git-town-branch.doubleclick-validate.parent=master
git-town-branch.master.parent=master
git-town-branch.code-refactoring.parent=master
git-town-branch.develop.parent=master
branch.develop.remote=origin
branch.develop.merge=refs/heads/develop
```

**Comment by hammenm** [comment]
```
git-town-branch.master.parent=master
```

This line is suspect, isn't it ?

**Comment by charlierudolph** [comment]
Yep there is an invalid entry that I believe creates an infinite loop:
```
git-town-branch.master.parent=master
```
Delete it with
```
git config --unset git-town-branch.master.parent
```
After your run that I believe your problem will be fixed.

@kevgo any thoughts on adding in some infinite loop protection?

**Comment by hammenm** [comment]
It is working as expected now, thank you for the help!

I am also glad to have show you this issue, if it can help you 👍

**Comment by kevgo** [comment]
@charlierudolph yes, some lightweight verification of data, as we read it, seems a good idea. In this case, the parent of `master` was set to `master`, Git Town could have easily aborted with an error message here.

**Comment by kevgo** [comment]
I have created #969 to track this. Closing this issue. Thanks for helping surface this edge case, @hammenm!
